# Baseline Colab — MOT15 + MOT16

Генерация `.npy` (det + ReID) и прогон оригинального DeepSORT на **6 sequences**.  
Оба набора генерируются одинаково через `generate_detections.py` → `MOT15_train/` и `MOT16_train/`.

In [1]:
DRIVE_RESOURCES = "/content/drive/MyDrive/DeepSORT/resources"

from google.colab import drive
drive.mount("/content/drive")

import os
assert os.path.isdir(DRIVE_RESOURCES), f"Папка не найдена: {DRIVE_RESOURCES}"

# Клонируем код (HTTPS, без SSH)
if not os.path.isdir("/content/DeepSORT_Project_CV"):
    !git clone https://github.com/Valeriia-Reznik-Dev/DeepSORT_Project_CV.git /content/DeepSORT_Project_CV

%cd /content/DeepSORT_Project_CV
!git pull

# Подключаем ваши данные с Drive
if os.path.islink("resources"):
    os.remove("resources")
elif os.path.isdir("resources"):
    !rm -rf resources
!ln -s "{DRIVE_RESOURCES}" resources

print("resources ->", os.path.realpath("resources"))

Mounted at /content/drive
Cloning into '/content/DeepSORT_Project_CV'...
remote: Enumerating objects: 493, done.
remote: Counting objects: 100% (493/493), done.
remote: Compressing objects: 100% (261/261), done.
remote: Total 493 (delta 284), reused 418 (delta 209), pack-reused 0 (from 0)
Receiving objects: 100% (493/493), 192.34 KiB | 1.49 MiB/s, done.
Resolving deltas: 100% (284/284), done.
/content/DeepSORT_Project_CV
Already up to date.
resources -> /content/drive/MyDrive/DeepSORT/resources

In [2]:
!pip install -q "numpy>=2.0" opencv-python scipy pyyaml

import numpy as np
print("NumPy", np.__version__)
assert np.__version__.split(".")[0] >= "2", (
    "numpy<2 обнаружен. Перезапустите рантайм (Runtime -> Restart session) и выполните ячейку заново."
)

import tensorflow as tf
print("TensorFlow", tf.__version__)
print("GPU", tf.config.list_physical_devices("GPU"))

NumPy 2.0.2
TensorFlow 2.20.0
GPU [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [3]:
import os

MOT15_SEQUENCES = ["TUD-Campus", "TUD-Stadtmitte", "KITTI-17", "PETS09-S2L1"]
MOT16_SEQUENCES = ["MOT16-09", "MOT16-11"]
DRIVE_RESOURCES = "/content/drive/MyDrive/DeepSORT/resources"

paths = {
    "model": os.path.join(DRIVE_RESOURCES, "networks", "mars-small128.pb"),
    "mot15_dir": "resources/detections/MOT15/train",
    "mot16_dir": "resources/detections/MOT16/train",
    "mot15_npy_dir": "resources/detections/MOT15_train",
    "mot16_npy_dir": "resources/detections/MOT16_train",
}

assert os.path.isfile(paths["model"]), f"Missing: {paths['model']}"

for seq in MOT15_SEQUENCES:
    assert os.path.isdir(os.path.join(paths["mot15_dir"], seq)), f"Missing MOT15 video: {seq}"
for seq in MOT16_SEQUENCES:
    assert os.path.isdir(os.path.join(paths["mot16_dir"], seq)), f"Missing MOT16 video: {seq}"

print("OK: model + MOT15/MOT16 videos on Drive")

OK: model + MOT15/MOT16 videos on Drive

In [4]:
import os
import time
from google.colab import drive

DRIVE_ROOT = "/content/drive"
DRIVE_RESOURCES = "/content/drive/MyDrive/DeepSORT/resources"
SRC_MODEL = os.path.join(DRIVE_RESOURCES, "networks", "mars-small128.pb")
MODEL = "/content/mars-small128.pb"


def ensure_drive() -> None:
    """Remount Drive if the FUSE mount is dead (OSError 107)."""
    try:
        with open(SRC_MODEL, "rb") as f:
            f.read(1)
    except OSError as exc:
        print(f"Drive mount unhealthy ({exc}); remounting ...")
        drive.mount(DRIVE_ROOT, force_remount=True)


def copy_from_drive(src: str, dst: str, *, chunk_size: int = 1024 * 1024, retries: int = 5) -> None:
    """Copy a Drive file to local disk; remount Drive on FUSE disconnect (errno 107)."""
    ensure_drive()
    src_size = os.path.getsize(src)
    if os.path.isfile(dst) and os.path.getsize(dst) == src_size:
        print(f"Already cached: {dst}")
        return

    last_err = None
    for attempt in range(1, retries + 1):
        try:
            with open(src, "rb") as fsrc, open(dst, "wb") as fdst:
                while True:
                    chunk = fsrc.read(chunk_size)
                    if not chunk:
                        break
                    fdst.write(chunk)
            if os.path.getsize(dst) == src_size:
                print(f"Copied {src_size / 1e6:.1f} MB -> {dst}")
                return
            last_err = OSError(f"size mismatch: got {os.path.getsize(dst)}, expected {src_size}")
        except OSError as exc:
            last_err = exc
            if os.path.isfile(dst):
                os.remove(dst)
            print(f"Drive copy failed ({exc}); remount + retry {attempt}/{retries} in 5s ...")
            time.sleep(5)
            ensure_drive()
            src_size = os.path.getsize(src)

    raise OSError(
        f"Could not copy {src} -> {dst}: {last_err}. "
        "Remount Drive: Runtime -> Restart session, rerun from cell 1, "
        "or drive.mount('/content/drive', force_remount=True)."
    )


copy_from_drive(SRC_MODEL, MODEL)
print("MODEL ->", MODEL)

# Кадры ниже читаются через симлинк resources -> Drive; убедимся, что монтирование живо.
ensure_drive()

# MOT15 + MOT16: один pipeline, generate_detections.py
!python tools/generate_detections.py \
    --model="{MODEL}" \
    --mot_dir=resources/detections/MOT15/train \
    --output_dir=resources/detections/MOT15_train

!python tools/generate_detections.py \
    --model="{MODEL}" \
    --mot_dir=resources/detections/MOT16/train \
    --output_dir=resources/detections/MOT16_train

Streaming output truncated to the last 5000 lines.
Frame 00323/00900
Frame 00324/00900
Frame 00325/00900
Frame 00326/00900
Frame 00327/00900
Frame 00328/00900
Frame 00329/00900
Frame 00330/00900
Frame 00331/00900
Frame 00332/00900
Frame 00333/00900
Frame 00334/00900
Frame 00335/00900
Frame 00336/00900
Frame 00337/00900
Frame 00338/00900
Frame 00339/00900
Frame 00340/00900
Frame 00341/00900
Frame 00342/00900
Frame 00343/00900
Frame 00344/00900
Frame 00345/00900
Frame 00346/00900
Frame 00347/00900
Frame 00348/00900
Frame 00349/00900
Frame 00350/00900
Frame 00351/00900
Frame 00352/00900
Frame 00353/00900
Frame 00354/00900
Frame 00355/00900
Frame 00356/00900
Frame 00357/00900
Frame 00358/00900
Frame 00359/00900
Frame 00360/00900
Frame 00361/00900
Frame 00362/00900
Frame 00363/00900
Frame 00364/00900
Frame 00365/00900
Frame 00366/00900
Frame 00367/00900
Frame 00368/00900
Frame 00369/00900
Frame 00370/00900
Frame 00371/00900
Frame 00372/00900
Frame 00373/00900
Frame 00374/00900
Frame 00375/00900
Frame 00376/00900
Frame 00377/00900
Frame 00378/00900
Frame 00379/00900
Frame 00380/00900
Frame 00381/00900
Frame 00382/00900
Frame 00383/00900
Frame 00384/00900
Frame 00385/00900
Frame 00386/00900
Frame 00387/00900
Frame 00388/00900
Frame 00389/00900
Frame 00390/00900
Frame 00391/00900
Frame 00392/00900
Frame 00393/00900
Frame 00394/00900
Frame 00395/00900
Frame 00396/00900
Frame 00397/00900
Frame 00398/00900
Frame 00399/00900
Frame 00400/00900
Frame 00401/00900
Frame 00402/00900
Frame 00403/00900
Frame 00404/00900
Frame 00405/00900
Frame 00406/00900
Frame 00407/00900
Frame 00408/00900
Frame 00409/00900
Frame 00410/00900
Frame 00411/00900
Frame 00412/00900
Frame 00413/00900
Frame 00414/00900
Frame 00415/00900
Frame 00416/00900
Frame 00417/00900
Frame 00418/00900
Frame 00419/00900
Frame 00420/00900
Frame 00421/00900
Frame 00422/00900
Frame 00423/00900
Frame 00424/00900
Frame 00425/00900
Frame 00426/00900
Frame 00427/00900
Frame 00428/00900
Frame 00429/00900
Frame 00430/00900
Frame 00431/00900
Frame 00432/00900
Frame 00433/00900
Frame 00434/00900
Frame 00435/00900
Frame 00436/00900
Frame 00437/00900
Frame 00438/00900
Frame 00439/00900
Frame 00440/00900
Frame 00441/00900
Frame 00442/00900
Frame 00443/00900
Frame 00444/00900
Frame 00445/00900
Frame 00446/00900
Frame 00447/00900
Frame 00448/00900
Frame 00449/00900
Frame 00450/00900
Frame 00451/00900
Frame 00452/00900
Frame 00453/00900
Frame 00454/00900
Frame 00455/00900
Frame 00456/00900
Frame 00457/00900
Frame 00458/00900
Frame 00459/00900
Frame 00460/00900
Frame 00461/00900
Frame 00462/00900
Frame 00463/00900
Frame 00464/00900
Frame 00465/00900
Frame 00466/00900
Frame 00467/00900
Frame 00468/00900
Frame 00469/00900
Frame 00470/00900
Frame 00471/00900
Frame 00472/00900
Frame 00473/00900
Frame 00474/00900
Frame 00475/00900
Frame 00476/00900
Frame 00477/00900
Frame 00478/00900
Frame 00479/00900
Frame 00480/00900
Frame 00481/00900
Frame 00482/00900
Frame 00483/00900
Frame 00484/00900
Frame 00485/00900
Frame 00486/00900
Frame 00487/00900
Frame 00488/00900
Frame 00489/00900
Frame 00490/00900
Frame 00491/00900
Frame 00492/00900
Frame 00493/00900
Frame 00494/00900
Frame 00495/00900
Frame 00496/00900
Frame 00497/00900
Frame 00498/00900
Frame 00499/00900
Frame 00500/00900
Frame 00501/00900
Frame 00502/00900
Frame 00503/00900
Frame 00504/00900
Frame 00505/00900
Frame 00506/00900
Frame 00507/00900
Frame 00508/00900
Frame 00509/00900
Frame 00510/00900
Frame 00511/00900
Frame 00512/00900
Frame 00513/00900
Frame 00514/00900
Frame 00515/00900
Frame 00516/00900
Frame 00517/00900
Frame 00518/00900
Frame 00519/00900
Frame 00520/00900
Frame 00521/00900
Frame 00522/00900
Frame 00523/00900
Frame 00524/00900
Frame 00525/00900
Frame 00526/00900
Frame 00527/00900
Frame 00528/00900
Frame 00529/00900
Frame 00530/00900
Frame 00531/00900
Frame 00532/00900
Frame 00533/00900
Frame 00534/00900
Frame 00535/00900
Frame 00536/00900
Frame 00537/00900
Frame 00538/00900
Frame 00539/00900
Frame 00540/00900
Frame 00541/00900
Frame 00542/00900
Frame 00543/00900
Frame 00544/00900
Frame 00545/00900
Frame 00546/00900
Frame 00547/00900
Frame 00548/00900
Frame 00549/00900
Frame 00550/00900
Frame 00551/00900
Frame 00552/00900
Frame 00553/00900
Frame 00554/00900
Frame 00555/00900
Frame 00556/00900
Frame 00557/00900
Frame 00558/00900
Frame 00559/00900
Frame 00560/00900
Frame 00561/00900
Frame 00562/00900
Frame 00563/00900
Frame 00564/00900
Frame 00565/00900
Frame 00566/00900
Frame 00567/00900
Frame 00568/00900
Frame 00569/00900
Frame 00570/00900
Frame 00571/00900
Frame 00572/00900
Frame 00573/00900
Frame 00574/00900
Frame 00575/00900
Frame 00576/00900
Frame 00577/00900
Frame 00578/00900
Frame 00579/00900
Frame 00580/00900
Frame 00581/00900
Frame 00582/00900
Frame 00583/00900
Frame 00584/00900
Frame 00585/00900
Frame 00586/00900
Frame 00587/00900
Frame 00588/00900
Frame 00589/00900
Frame 00590/00900
Frame 00591/00900
Frame 00592/00900
Frame 00593/00900
Frame 00594/00900
Frame 00595/00900
Frame 00596/00900
Frame 00597/00900
Frame 00598/00900
Frame 00599/00900
Frame 00600/00900
Frame 00601/00900
Frame 00602/00900
Frame 00603/00900
Frame 00604/00900
Frame 00605/00900
Frame 00606/00900
Frame 00607/00900
Frame 00608/00900
Frame 00609/00900
Frame 00610/00900
Frame 00611/00900
Frame 00612/00900
Frame 00613/00900
Frame 00614/00900
Frame 00615/00900
Frame 00616/00900
Frame 00617/00900
Frame 00618/00900
Frame 00619/00900
Frame 00620/00900
Frame 00621/00900
Frame 00622/00900
Frame 00623/00900
Frame 00624/00900
Frame 00625/00900
Frame 00626/00900
Frame 00627/00900
Frame 00628/00900
Frame 00629/00900
Frame 00630/00900
Frame 00631/00900
Frame 00632/00900
Frame 00633/00900
Frame 00634/00900
Frame 00635/00900
Frame 00636/00900
Frame 00637/00900
Frame 00638/00900
Frame 00639/00900
Frame 00640/00900
Frame 00641/00900
Frame 00642/00900
Frame 00643/00900
Frame 00644/00900
Frame 00645/00900
Frame 00646/00900
Frame 00647/00900
Frame 00648/00900
Frame 00649/00900
Frame 00650/00900
Frame 00651/00900
Frame 00652/00900
Frame 00653/00900
Frame 00654/00900
Frame 00655/00900
Frame 00656/00900
Frame 00657/00900
Frame 00658/00900
Frame 00659/00900
Frame 00660/00900
Frame 00661/00900
Frame 00662/00900
Frame 00663/00900
Frame 00664/00900
Frame 00665/00900
Frame 00666/00900
Frame 00667/00900
Frame 00668/00900
Frame 00669/00900
Frame 00670/00900
Frame 00671/00900
Frame 00672/00900
Frame 00673/00900
Frame 00674/00900
Frame 00675/00900
Frame 00676/00900
Frame 00677/00900
Frame 00678/00900
Frame 00679/00900
Frame 00680/00900
Frame 00681/00900
Frame 00682/00900
Frame 00683/00900
Frame 00684/00900
Frame 00685/00900
Frame 00686/00900
Frame 00687/00900
Frame 00688/00900
Frame 00689/00900
Frame 00690/00900
Frame 00691/00900
Frame 00692/00900
Frame 00693/00900
Frame 00694/00900
Frame 00695/00900
Frame 00696/00900
Frame 00697/00900
Frame 00698/00900
Frame 00699/00900
Frame 00700/00900
Frame 00701/00900
Frame 00702/00900
Frame 00703/00900
Frame 00704/00900
Frame 00705/00900
Frame 00706/00900
Frame 00707/00900
Frame 00708/00900
Frame 00709/00900
Frame 00710/00900
Frame 00711/00900
Frame 00712/00900
Frame 00713/00900
Frame 00714/00900
Frame 00715/00900
Frame 00716/00900
Frame 00717/00900
Frame 00718/00900
Frame 00719/00900
Frame 00720/00900
Frame 00721/00900
Frame 00722/00900
Frame 00723/00900
Frame 00724/00900
Frame 00725/00900
Frame 00726/00900
Frame 00727/00900
Frame 00728/00900
Frame 00729/00900
Frame 00730/00900
Frame 00731/00900
Frame 00732/00900
Frame 00733/00900
Frame 00734/00900
Frame 00735/00900
Frame 00736/00900
Frame 00737/00900
Frame 00738/00900
Frame 00739/00900
Frame 00740/00900
Frame 00741/00900
Frame 00742/00900
Frame 00743/00900
Frame 00744/00900
Frame 00745/00900
Frame 00746/00900
Frame 00747/00900
Frame 00748/00900
Frame 00749/00900
Frame 00750/00900
Frame 00751/00900
Frame 00752/00900
Frame 00753/00900
Frame 00754/00900
Frame 00755/00900
Frame 00756/00900
Frame 00757/00900
Frame 00758/00900
Frame 00759/00900
Frame 00760/00900
Frame 00761/00900
Frame 00762/00900
Frame 00763/00900
Frame 00764/00900
Frame 00765/00900
Frame 00766/00900
Frame 00767/00900
Frame 00768/00900
Frame 00769/00900
Frame 00770/00900
Frame 00771/00900
Frame 00772/00900
Frame 00773/00900
Frame 00774/00900
Frame 00775/00900
Frame 00776/00900
Frame 00777/00900
Frame 00778/00900
Frame 00779/00900
Frame 00780/00900
Frame 00781/00900
Frame 00782/00900
Frame 00783/00900
Frame 00784/00900
Frame 00785/00900
Frame 00786/00900
Frame 00787/00900
Frame 00788/00900
Frame 00789/00900
Frame 00790/00900
Frame 00791/00900
Frame 00792/00900
Frame 00793/00900
Frame 00794/00900
Frame 00795/00900
Frame 00796/00900
Frame 00797/00900
Frame 00798/00900
Frame 00799/00900
Frame 00800/00900
Frame 00801/00900
Frame 00802/00900
Frame 00803/00900
Frame 00804/00900
Frame 00805/00900
Frame 00806/00900
Frame 00807/00900
Frame 00808/00900
Frame 00809/00900
Frame 00810/00900
Frame 00811/00900
Frame 00812/00900
Frame 00813/00900
Frame 00814/00900
Frame 00815/00900
Frame 00816/00900
Frame 00817/00900
Frame 00818/00900
Frame 00819/00900
Frame 00820/00900
Frame 00821/00900
Frame 00822/00900
Frame 00823/00900
Frame 00824/00900
Frame 00825/00900
Frame 00826/00900
Frame 00827/00900
Frame 00828/00900
Frame 00829/00900
Frame 00830/00900
Frame 00831/00900
Frame 00832/00900
Frame 00833/00900
Frame 00834/00900
Frame 00835/00900
Frame 00836/00900
Frame 00837/00900
Frame 00838/00900
Frame 00839/00900
Frame 00840/00900
Frame 00841/00900
Frame 00842/00900
Frame 00843/00900
Frame 00844/00900
Frame 00845/00900
Frame 00846/00900
Frame 00847/00900
Frame 00848/00900
Frame 00849/00900
Frame 00850/00900
Frame 00851/00900
Frame 00852/00900
Frame 00853/00900
Frame 00854/00900
Frame 00855/00900
Frame 00856/00900
Frame 00857/00900
Frame 00858/00900
Frame 00859/00900
Frame 00860/00900
Frame 00861/00900
Frame 00862/00900
Frame 00863/00900
Frame 00864/00900
Frame 00865/00900
Frame 00866/00900
Frame 00867/00900
Frame 00868/00900
Frame 00869/00900
Frame 00870/00900
Frame 00871/00900
Frame 00872/00900
Frame 00873/00900
Frame 00874/00900
Frame 00875/00900
Frame 00876/00900
Frame 00877/00900
Frame 00878/00900
Frame 00879/00900
Frame 00880/00900
Frame 00881/00900
Frame 00882/00900
Frame 00883/00900
Frame 00884/00900
Frame 00885/00900
Frame 00886/00900
Frame 00887/00900
Frame 00888/00900
Frame 00889/00900
Frame 00890/00900
Frame 00891/00900
Frame 00892/00900
Frame 00893/00900
Frame 00894/00900
Frame 00895/00900
Frame 00896/00900
Frame 00897/00900
Frame 00898/00900
Frame 00899/00900
Frame 00900/00900
Processing MOT16-09
Frame 00001/00525
Frame 00002/00525
Frame 00003/00525
Frame 00004/00525
Frame 00005/00525
Frame 00006/00525
Frame 00007/00525
Frame 00008/00525
Frame 00009/00525
Frame 00010/00525
Frame 00011/00525
Frame 00012/00525
Frame 00013/00525
Frame 00014/00525
Frame 00015/00525
Frame 00016/00525
Frame 00017/00525
Frame 00018/00525
Frame 00019/00525
Frame 00020/00525
Frame 00021/00525
Frame 00022/00525
Frame 00023/00525
Frame 00024/00525
Frame 00025/00525
Frame 00026/00525
Frame 00027/00525
Frame 00028/00525
Frame 00029/00525
Frame 00030/00525
Frame 00031/00525
Frame 00032/00525
Frame 00033/00525
Frame 00034/00525
Frame 00035/00525
Frame 00036/00525
Frame 00037/00525
Frame 00038/00525
Frame 00039/00525
Frame 00040/00525
Frame 00041/00525
Frame 00042/00525
Frame 00043/00525
Frame 00044/00525
Frame 00045/00525
Frame 00046/00525
Frame 00047/00525
Frame 00048/00525
Frame 00049/00525
Frame 00050/00525
Frame 00051/00525
Frame 00052/00525
Frame 00053/00525
Frame 00054/00525
Frame 00055/00525
Frame 00056/00525
Frame 00057/00525
Frame 00058/00525
Frame 00059/00525
Frame 00060/00525
Frame 00061/00525
Frame 00062/00525
Frame 00063/00525
Frame 00064/00525
Frame 00065/00525
Frame 00066/00525
Frame 00067/00525
Frame 00068/00525
Frame 00069/00525
Frame 00070/00525
Frame 00071/00525
Frame 00072/00525
Frame 00073/00525
Frame 00074/00525
Frame 00075/00525
Frame 00076/00525
Frame 00077/00525
Frame 00078/00525
Frame 00079/00525
Frame 00080/00525
Frame 00081/00525
Frame 00082/00525
Frame 00083/00525
Frame 00084/00525
Frame 00085/00525
Frame 00086/00525
Frame 00087/00525
Frame 00088/00525
Frame 00089/00525
Frame 00090/00525
Frame 00091/00525
Frame 00092/00525
Frame 00093/00525
Frame 00094/00525
Frame 00095/00525
Frame 00096/00525
Frame 00097/00525
Frame 00098/00525
Frame 00099/00525
Frame 00100/00525
Frame 00101/00525
Frame 00102/00525
Frame 00103/00525
Frame 00104/00525
Frame 00105/00525
Frame 00106/00525
Frame 00107/00525
Frame 00108/00525
Frame 00109/00525
Frame 00110/00525
Frame 00111/00525
Frame 00112/00525
Frame 00113/00525
Frame 00114/00525
Frame 00115/00525
Frame 00116/00525
Frame 00117/00525
Frame 00118/00525
Frame 00119/00525
Frame 00120/00525
Frame 00121/00525
Frame 00122/00525
Frame 00123/00525
Frame 00124/00525
Frame 00125/00525
Frame 00126/00525
Frame 00127/00525
Frame 00128/00525
Frame 00129/00525
Frame 00130/00525
Frame 00131/00525
Frame 00132/00525
Frame 00133/00525
Frame 00134/00525
Frame 00135/00525
Frame 00136/00525
Frame 00137/00525
Frame 00138/00525
Frame 00139/00525
Frame 00140/00525
Frame 00141/00525
Frame 00142/00525
Frame 00143/00525
Frame 00144/00525
Frame 00145/00525
Frame 00146/00525
Frame 00147/00525
Frame 00148/00525
Frame 00149/00525
Frame 00150/00525
Frame 00151/00525
Frame 00152/00525
Frame 00153/00525
Frame 00154/00525
Frame 00155/00525
Frame 00156/00525
Frame 00157/00525
Frame 00158/00525
Frame 00159/00525
Frame 00160/00525
Frame 00161/00525
Frame 00162/00525
Frame 00163/00525
Frame 00164/00525
Frame 00165/00525
Frame 00166/00525
Frame 00167/00525
Frame 00168/00525
Frame 00169/00525
Frame 00170/00525
Frame 00171/00525
Frame 00172/00525
Frame 00173/00525
Frame 00174/00525
Frame 00175/00525
Frame 00176/00525
Frame 00177/00525
Frame 00178/00525
Frame 00179/00525
Frame 00180/00525
Frame 00181/00525
Frame 00182/00525
Frame 00183/00525
Frame 00184/00525
Frame 00185/00525
Frame 00186/00525
Frame 00187/00525
Frame 00188/00525
Frame 00189/00525
Frame 00190/00525
Frame 00191/00525
Frame 00192/00525
Frame 00193/00525
Frame 00194/00525
Frame 00195/00525
Frame 00196/00525
Frame 00197/00525
Frame 00198/00525
Frame 00199/00525
Frame 00200/00525
Frame 00201/00525
Frame 00202/00525
Frame 00203/00525
Frame 00204/00525
Frame 00205/00525
Frame 00206/00525
Frame 00207/00525
Frame 00208/00525
Frame 00209/00525
Frame 00210/00525
Frame 00211/00525
Frame 00212/00525
Frame 00213/00525
Frame 00214/00525
Frame 00215/00525
Frame 00216/00525
Frame 00217/00525
Frame 00218/00525
Frame 00219/00525
Frame 00220/00525
Frame 00221/00525
Frame 00222/00525
Frame 00223/00525
Frame 00224/00525
Frame 00225/00525
Frame 00226/00525
Frame 00227/00525
Frame 00228/00525
Frame 00229/00525
Frame 00230/00525
Frame 00231/00525
Frame 00232/00525
Frame 00233/00525
Frame 00234/00525
Frame 00235/00525
Frame 00236/00525
Frame 00237/00525
Frame 00238/00525
Frame 00239/00525
Frame 00240/00525
Frame 00241/00525
Frame 00242/00525
Frame 00243/00525
Frame 00244/00525
Frame 00245/00525
Frame 00246/00525
Frame 00247/00525
Frame 00248/00525
Frame 00249/00525
Frame 00250/00525
Frame 00251/00525
Frame 00252/00525
Frame 00253/00525
Frame 00254/00525
Frame 00255/00525
Frame 00256/00525
Frame 00257/00525
Frame 00258/00525
Frame 00259/00525
Frame 00260/00525
Frame 00261/00525
Frame 00262/00525
Frame 00263/00525
Frame 00264/00525
Frame 00265/00525
Frame 00266/00525
Frame 00267/00525
Frame 00268/00525
Frame 00269/00525
Frame 00270/00525
Frame 00271/00525
Frame 00272/00525
Frame 00273/00525
Frame 00274/00525
Frame 00275/00525
Frame 00276/00525
Frame 00277/00525
Frame 00278/00525
Frame 00279/00525
Frame 00280/00525
Frame 00281/00525
Frame 00282/00525
Frame 00283/00525
Frame 00284/00525
Frame 00285/00525
Frame 00286/00525
Frame 00287/00525
Frame 00288/00525
Frame 00289/00525
Frame 00290/00525
Frame 00291/00525
Frame 00292/00525
Frame 00293/00525
Frame 00294/00525
Frame 00295/00525
Frame 00296/00525
Frame 00297/00525
Frame 00298/00525
Frame 00299/00525
Frame 00300/00525
Frame 00301/00525
Frame 00302/00525
Frame 00303/00525
Frame 00304/00525
Frame 00305/00525
Frame 00306/00525
Frame 00307/00525
Frame 00308/00525
Frame 00309/00525
Frame 00310/00525
Frame 00311/00525
Frame 00312/00525
Frame 00313/00525
Frame 00314/00525
Frame 00315/00525
Frame 00316/00525
Frame 00317/00525
Frame 00318/00525
Frame 00319/00525
Frame 00320/00525
Frame 00321/00525
Frame 00322/00525
Frame 00323/00525
Frame 00324/00525
Frame 00325/00525
Frame 00326/00525
Frame 00327/00525
Frame 00328/00525
Frame 00329/00525
Frame 00330/00525
Frame 00331/00525
Frame 00332/00525
Frame 00333/00525
Frame 00334/00525
Frame 00335/00525
Frame 00336/00525
Frame 00337/00525
Frame 00338/00525
Frame 00339/00525
Frame 00340/00525
Frame 00341/00525
Frame 00342/00525
Frame 00343/00525
Frame 00344/00525
Frame 00345/00525
Frame 00346/00525
Frame 00347/00525
Frame 00348/00525
Frame 00349/00525
Frame 00350/00525
Frame 00351/00525
Frame 00352/00525
Frame 00353/00525
Frame 00354/00525
Frame 00355/00525
Frame 00356/00525
Frame 00357/00525
Frame 00358/00525
Frame 00359/00525
Frame 00360/00525
Frame 00361/00525
Frame 00362/00525
Frame 00363/00525
Frame 00364/00525
Frame 00365/00525
Frame 00366/00525
Frame 00367/00525
Frame 00368/00525
Frame 00369/00525
Frame 00370/00525
Frame 00371/00525
Frame 00372/00525
Frame 00373/00525
Frame 00374/00525
Frame 00375/00525
Frame 00376/00525
Frame 00377/00525
Frame 00378/00525
Frame 00379/00525
Frame 00380/00525
Frame 00381/00525
Frame 00382/00525
Frame 00383/00525
Frame 00384/00525
Frame 00385/00525
Frame 00386/00525
Frame 00387/00525
Frame 00388/00525
Frame 00389/00525
Frame 00390/00525
Frame 00391/00525
Frame 00392/00525
Frame 00393/00525
Frame 00394/00525
Frame 00395/00525
Frame 00396/00525
Frame 00397/00525
Frame 00398/00525
Frame 00399/00525
Frame 00400/00525
Frame 00401/00525
Frame 00402/00525
Frame 00403/00525
Frame 00404/00525
Frame 00405/00525
Frame 00406/00525
Frame 00407/00525
Frame 00408/00525
Frame 00409/00525
Frame 00410/00525
Frame 00411/00525
Frame 00412/00525
Frame 00413/00525
Frame 00414/00525
Frame 00415/00525
Frame 00416/00525
Frame 00417/00525
Frame 00418/00525
Frame 00419/00525
Frame 00420/00525
Frame 00421/00525
Frame 00422/00525
Frame 00423/00525
Frame 00424/00525
Frame 00425/00525
Frame 00426/00525
Frame 00427/00525
Frame 00428/00525
Frame 00429/00525
Frame 00430/00525
Frame 00431/00525
Frame 00432/00525
Frame 00433/00525
Frame 00434/00525
Frame 00435/00525
Frame 00436/00525
Frame 00437/00525
Frame 00438/00525
Frame 00439/00525
Frame 00440/00525
Frame 00441/00525
Frame 00442/00525
Frame 00443/00525
Frame 00444/00525
Frame 00445/00525
Frame 00446/00525
Frame 00447/00525
Frame 00448/00525
Frame 00449/00525
Frame 00450/00525
Frame 00451/00525
Frame 00452/00525
Frame 00453/00525
Frame 00454/00525
Frame 00455/00525
Frame 00456/00525
Frame 00457/00525
Frame 00458/00525
Frame 00459/00525
Frame 00460/00525
Frame 00461/00525
Frame 00462/00525
Frame 00463/00525
Frame 00464/00525
Frame 00465/00525
Frame 00466/00525
Frame 00467/00525
Frame 00468/00525
Frame 00469/00525
Frame 00470/00525
Frame 00471/00525
Frame 00472/00525
Frame 00473/00525
Frame 00474/00525
Frame 00475/00525
Frame 00476/00525
Frame 00477/00525
Frame 00478/00525
Frame 00479/00525
Frame 00480/00525
Frame 00481/00525
Frame 00482/00525
Frame 00483/00525
Frame 00484/00525
Frame 00485/00525
Frame 00486/00525
Frame 00487/00525
Frame 00488/00525
Frame 00489/00525
Frame 00490/00525
Frame 00491/00525
Frame 00492/00525
Frame 00493/00525
Frame 00494/00525
Frame 00495/00525
Frame 00496/00525
Frame 00497/00525
Frame 00498/00525
Frame 00499/00525
Frame 00500/00525
Frame 00501/00525
Frame 00502/00525
Frame 00503/00525
Frame 00504/00525
Frame 00505/00525
Frame 00506/00525
Frame 00507/00525
Frame 00508/00525
Frame 00509/00525
Frame 00510/00525
Frame 00511/00525
Frame 00512/00525
Frame 00513/00525
Frame 00514/00525
Frame 00515/00525
Frame 00516/00525
Frame 00517/00525
Frame 00518/00525
Frame 00519/00525
Frame 00520/00525
Frame 00521/00525
Frame 00522/00525
Frame 00523/00525
Frame 00524/00525
Frame 00525/00525
Processing MOT16-04
Frame 00001/01050
Frame 00002/01050
Frame 00003/01050

In [5]:
import numpy as np

ALL_SEQUENCES = [
    (paths["mot15_npy_dir"], MOT15_SEQUENCES),
    (paths["mot16_npy_dir"], MOT16_SEQUENCES),
]

for npy_dir, seqs in ALL_SEQUENCES:
    print(f"--- {npy_dir}")
    for seq in seqs:
        path = os.path.join(npy_dir, f"{seq}.npy")
        assert os.path.isfile(path), f"Missing: {path}"
        print(seq, np.load(path).shape)

print("OK: all 6 .npy ready")

--- resources/detections/MOT15_train
TUD-Campus (322, 138)
TUD-Stadtmitte (1129, 138)
KITTI-17 (552, 138)
PETS09-S2L1 (5578, 138)
--- resources/detections/MOT16_train
MOT16-09 (5976, 138)
MOT16-11 (8590, 138)
OK: all 6 .npy ready

In [6]:
!python scripts/run_baseline.py

Running TUD-Campus
Processing frame 00001
Processing frame 00002
Processing frame 00003
Processing frame 00004
Processing frame 00005
Processing frame 00006
Processing frame 00007
Processing frame 00008
Processing frame 00009
Processing frame 00010
Processing frame 00011
Processing frame 00012
Processing frame 00013
Processing frame 00014
Processing frame 00015
Processing frame 00016
Processing frame 00017
Processing frame 00018
Processing frame 00019
Processing frame 00020
Processing frame 00021
Processing frame 00022
Processing frame 00023
Processing frame 00024
Processing frame 00025
Processing frame 00026
Processing frame 00027
Processing frame 00028
Processing frame 00029
Processing frame 00030
Processing frame 00031
Processing frame 00032
Processing frame 00033
Processing frame 00034
Processing frame 00035
Processing frame 00036
Processing frame 00037
Processing frame 00038
Processing frame 00039
Processing frame 00040
Processing frame 00041
Processing frame 00042
Processing frame 00043
Processing frame 00044
Processing frame 00045
Processing frame 00046
Processing frame 00047
Processing frame 00048
Processing frame 00049
Processing frame 00050
Processing frame 00051
Processing frame 00052
Processing frame 00053
Processing frame 00054
Processing frame 00055
Processing frame 00056
Processing frame 00057
Processing frame 00058
Processing frame 00059
Processing frame 00060
Processing frame 00061
Processing frame 00062
Processing frame 00063
Processing frame 00064
Processing frame 00065
Processing frame 00066
Processing frame 00067
Processing frame 00068
Processing frame 00069
Processing frame 00070
Processing frame 00071
Running TUD-Stadtmitte
Processing frame 00001
Processing frame 00002
Processing frame 00003
Processing frame 00004
Processing frame 00005
Processing frame 00006
Processing frame 00007
Processing frame 00008
Processing frame 00009
Processing frame 00010
Processing frame 00011
Processing frame 00012
Processing frame 00013
Processing frame 00014
Processing frame 00015
Processing frame 00016
Processing frame 00017
Processing frame 00018
Processing frame 00019
Processing frame 00020
Processing frame 00021
Processing frame 00022
Processing frame 00023
Processing frame 00024
Processing frame 00025
Processing frame 00026
Processing frame 00027
Processing frame 00028
Processing frame 00029
Processing frame 00030
Processing frame 00031
Processing frame 00032
Processing frame 00033
Processing frame 00034
Processing frame 00035
Processing frame 00036
Processing frame 00037
Processing frame 00038
Processing frame 00039
Processing frame 00040
Processing frame 00041
Processing frame 00042
Processing frame 00043
Processing frame 00044
Processing frame 00045
Processing frame 00046
Processing frame 00047
Processing frame 00048
Processing frame 00049
Processing frame 00050
Processing frame 00051
Processing frame 00052
Processing frame 00053
Processing frame 00054
Processing frame 00055
Processing frame 00056
Processing frame 00057
Processing frame 00058
Processing frame 00059
Processing frame 00060
Processing frame 00061
Processing frame 00062
Processing frame 00063
Processing frame 00064
Processing frame 00065
Processing frame 00066
Processing frame 00067
Processing frame 00068
Processing frame 00069
Processing frame 00070
Processing frame 00071
Processing frame 00072
Processing frame 00073
Processing frame 00074
Processing frame 00075
Processing frame 00076
Processing frame 00077
Processing frame 00078
Processing frame 00079
Processing frame 00080
Processing frame 00081
Processing frame 00082
Processing frame 00083
Processing frame 00084
Processing frame 00085
Processing frame 00086
Processing frame 00087
Processing frame 00088
Processing frame 00089
Processing frame 00090
Processing frame 00091
Processing frame 00092
Processing frame 00093
Processing frame 00094
Processing frame 00095
Processing frame 00096
Processing frame 00097
Processing frame 00098
Processing frame 00099
Processing frame 00100
Processing frame 00101
Processing frame 00102
Processing frame 00103
Processing frame 00104
Processing frame 00105
Processing frame 00106
Processing frame 00107
Processing frame 00108
Processing frame 00109
Processing frame 00110
Processing frame 00111
Processing frame 00112
Processing frame 00113
Processing frame 00114
Processing frame 00115
Processing frame 00116
Processing frame 00117
Processing frame 00118
Processing frame 00119
Processing frame 00120
Processing frame 00121
Processing frame 00122
Processing frame 00123
Processing frame 00124
Processing frame 00125
Processing frame 00126
Processing frame 00127
Processing frame 00128
Processing frame 00129
Processing frame 00130
Processing frame 00131
Processing frame 00132
Processing frame 00133
Processing frame 00134
Processing frame 00135
Processing frame 00136
Processing frame 00137
Processing frame 00138
Processing frame 00139
Processing frame 00140
Processing frame 00141
Processing frame 00142
Processing frame 00143
Processing frame 00144
Processing frame 00145
Processing frame 00146
Processing frame 00147
Processing frame 00148
Processing frame 00149
Processing frame 00150
Processing frame 00151
Processing frame 00152
Processing frame 00153
Processing frame 00154
Processing frame 00155
Processing frame 00156
Processing frame 00157
Processing frame 00158
Processing frame 00159
Processing frame 00160
Processing frame 00161
Processing frame 00162
Processing frame 00163
Processing frame 00164
Processing frame 00165
Processing frame 00166
Processing frame 00167
Processing frame 00168
Processing frame 00169
Processing frame 00170
Processing frame 00171
Processing frame 00172
Processing frame 00173
Processing frame 00174
Processing frame 00175
Processing frame 00176
Processing frame 00177
Processing frame 00178
Processing frame 00179
Running KITTI-17
Processing frame 00001
Processing frame 00002
Processing frame 00003
Processing frame 00004
Processing frame 00005
Processing frame 00006
Processing frame 00007
Processing frame 00008
Processing frame 00009
Processing frame 00010
Processing frame 00011
Processing frame 00012
Processing frame 00013
Processing frame 00014
Processing frame 00015
Processing frame 00016
Processing frame 00017
Processing frame 00018
Processing frame 00019
Processing frame 00020
Processing frame 00021
Processing frame 00022
Processing frame 00023
Processing frame 00024
Processing frame 00025
Processing frame 00026
Processing frame 00027
Processing frame 00028
Processing frame 00029
Processing frame 00030
Processing frame 00031
Processing frame 00032
Processing frame 00033
Processing frame 00034
Processing frame 00035
Processing frame 00036
Processing frame 00037
Processing frame 00038
Processing frame 00039
Processing frame 00040
Processing frame 00041
Processing frame 00042
Processing frame 00043
Processing frame 00044
Processing frame 00045
Processing frame 00046
Processing frame 00047
Processing frame 00048
Processing frame 00049
Processing frame 00050
Processing frame 00051
Processing frame 00052
Processing frame 00053
Processing frame 00054
Processing frame 00055
Processing frame 00056
Processing frame 00057
Processing frame 00058
Processing frame 00059
Processing frame 00060
Processing frame 00061
Processing frame 00062
Processing frame 00063
Processing frame 00064
Processing frame 00065
Processing frame 00066
Processing frame 00067
Processing frame 00068
Processing frame 00069
Processing frame 00070
Processing frame 00071
Processing frame 00072
Processing frame 00073
Processing frame 00074
Processing frame 00075
Processing frame 00076
Processing frame 00077
Processing frame 00078
Processing frame 00079
Processing frame 00080
Processing frame 00081
Processing frame 00082
Processing frame 00083
Processing frame 00084
Processing frame 00085
Processing frame 00086
Processing frame 00087
Processing frame 00088
Processing frame 00089
Processing frame 00090
Processing frame 00091
Processing frame 00092
Processing frame 00093
Processing frame 00094
Processing frame 00095
Processing frame 00096
Processing frame 00097
Processing frame 00098
Processing frame 00099
Processing frame 00100
Processing frame 00101
Processing frame 00102
Processing frame 00103
Processing frame 00104
Processing frame 00105
Processing frame 00106
Processing frame 00107
Processing frame 00108
Processing frame 00109
Processing frame 00110
Processing frame 00111
Processing frame 00112
Processing frame 00113
Processing frame 00114
Processing frame 00115
Processing frame 00116
Processing frame 00117
Processing frame 00118
Processing frame 00119
Processing frame 00120
Processing frame 00121
Processing frame 00122
Processing frame 00123
Processing frame 00124
Processing frame 00125
Processing frame 00126
Processing frame 00127
Processing frame 00128
Processing frame 00129
Processing frame 00130
Processing frame 00131
Processing frame 00132
Processing frame 00133
Processing frame 00134
Processing frame 00135
Processing frame 00136
Processing frame 00137
Processing frame 00138
Processing frame 00139
Processing frame 00140
Processing frame 00141
Processing frame 00142
Processing frame 00143
Processing frame 00144
Processing frame 00145
Running PETS09-S2L1
Processing frame 00001
Processing frame 00002
Processing frame 00003
Processing frame 00004
Processing frame 00005
Processing frame 00006
Processing frame 00007
Processing frame 00008
Processing frame 00009
Processing frame 00010
Processing frame 00011
Processing frame 00012
Processing frame 00013
Processing frame 00014
Processing frame 00015
Processing frame 00016
Processing frame 00017
Processing frame 00018
Processing frame 00019
Processing frame 00020
Processing frame 00021
Processing frame 00022
Processing frame 00023
Processing frame 00024
Processing frame 00025
Processing frame 00026
Processing frame 00027
Processing frame 00028
Processing frame 00029
Processing frame 00030
Processing frame 00031
Processing frame 00032
Processing frame 00033
Processing frame 00034
Processing frame 00035
Processing frame 00036
Processing frame 00037
Processing frame 00038
Processing frame 00039
Processing frame 00040
Processing frame 00041
Processing frame 00042
Processing frame 00043
Processing frame 00044
Processing frame 00045
Processing frame 00046
Processing frame 00047
Processing frame 00048
Processing frame 00049
Processing frame 00050
Processing frame 00051
Processing frame 00052
Processing frame 00053
Processing frame 00054
Processing frame 00055
Processing frame 00056
Processing frame 00057
Processing frame 00058
Processing frame 00059
Processing frame 00060
Processing frame 00061
Processing frame 00062
Processing frame 00063
Processing frame 00064
Processing frame 00065
Processing frame 00066
Processing frame 00067
Processing frame 00068
Processing frame 00069
Processing frame 00070
Processing frame 00071
Processing frame 00072
Processing frame 00073
Processing frame 00074
Processing frame 00075
Processing frame 00076
Processing frame 00077
Processing frame 00078
Processing frame 00079
Processing frame 00080
Processing frame 00081
Processing frame 00082
Processing frame 00083
Processing frame 00084
Processing frame 00085
Processing frame 00086
Processing frame 00087
Processing frame 00088
Processing frame 00089
Processing frame 00090
Processing frame 00091
Processing frame 00092
Processing frame 00093
Processing frame 00094
Processing frame 00095
Processing frame 00096
Processing frame 00097
Processing frame 00098
Processing frame 00099
Processing frame 00100
Processing frame 00101
Processing frame 00102
Processing frame 00103
Processing frame 00104
Processing frame 00105
Processing frame 00106
Processing frame 00107
Processing frame 00108
Processing frame 00109
Processing frame 00110
Processing frame 00111
Processing frame 00112
Processing frame 00113
Processing frame 00114
Processing frame 00115
Processing frame 00116
Processing frame 00117
Processing frame 00118
Processing frame 00119
Processing frame 00120
Processing frame 00121
Processing frame 00122
Processing frame 00123
Processing frame 00124
Processing frame 00125
Processing frame 00126
Processing frame 00127
Processing frame 00128
Processing frame 00129
Processing frame 00130
Processing frame 00131
Processing frame 00132
Processing frame 00133
Processing frame 00134
Processing frame 00135
Processing frame 00136
Processing frame 00137
Processing frame 00138
Processing frame 00139
Processing frame 00140
Processing frame 00141
Processing frame 00142
Processing frame 00143
Processing frame 00144
Processing frame 00145
Processing frame 00146
Processing frame 00147
Processing frame 00148
Processing frame 00149
Processing frame 00150
Processing frame 00151
Processing frame 00152
Processing frame 00153
Processing frame 00154
Processing frame 00155
Processing frame 00156
Processing frame 00157
Processing frame 00158
Processing frame 00159
Processing frame 00160
Processing frame 00161
Processing frame 00162
Processing frame 00163
Processing frame 00164
Processing frame 00165
Processing frame 00166
Processing frame 00167
Processing frame 00168
Processing frame 00169
Processing frame 00170
Processing frame 00171
Processing frame 00172
Processing frame 00173
Processing frame 00174
Processing frame 00175
Processing frame 00176
Processing frame 00177
Processing frame 00178
Processing frame 00179
Processing frame 00180
Processing frame 00181
Processing frame 00182
Processing frame 00183
Processing frame 00184
Processing frame 00185
Processing frame 00186
Processing frame 00187
Processing frame 00188
Processing frame 00189
Processing frame 00190
Processing frame 00191
Processing frame 00192
Processing frame 00193
Processing frame 00194
Processing frame 00195
Processing frame 00196
Processing frame 00197
Processing frame 00198
Processing frame 00199
Processing frame 00200
Processing frame 00201
Processing frame 00202
Processing frame 00203
Processing frame 00204
Processing frame 00205
Processing frame 00206
Processing frame 00207
Processing frame 00208
Processing frame 00209
Processing frame 00210
Processing frame 00211
Processing frame 00212
Processing frame 00213
Processing frame 00214
Processing frame 00215
Processing frame 00216
Processing frame 00217
Processing frame 00218
Processing frame 00219
Processing frame 00220
Processing frame 00221
Processing frame 00222
Processing frame 00223
Processing frame 00224
Processing frame 00225
Processing frame 00226
Processing frame 00227
Processing frame 00228
Processing frame 00229
Processing frame 00230
Processing frame 00231
Processing frame 00232
Processing frame 00233
Processing frame 00234
Processing frame 00235
Processing frame 00236
Processing frame 00237
Processing frame 00238
Processing frame 00239
Processing frame 00240
Processing frame 00241
Processing frame 00242
Processing frame 00243
Processing frame 00244
Processing frame 00245
Processing frame 00246
Processing frame 00247
Processing frame 00248
Processing frame 00249
Processing frame 00250
Processing frame 00251
Processing frame 00252
Processing frame 00253
Processing frame 00254
Processing frame 00255
Processing frame 00256
Processing frame 00257
Processing frame 00258
Processing frame 00259
Processing frame 00260
Processing frame 00261
Processing frame 00262
Processing frame 00263
Processing frame 00264
Processing frame 00265
Processing frame 00266
Processing frame 00267
Processing frame 00268
Processing frame 00269
Processing frame 00270
Processing frame 00271
Processing frame 00272
Processing frame 00273
Processing frame 00274
Processing frame 00275
Processing frame 00276
Processing frame 00277
Processing frame 00278
Processing frame 00279
Processing frame 00280
Processing frame 00281
Processing frame 00282
Processing frame 00283
Processing frame 00284
Processing frame 00285
Processing frame 00286
Processing frame 00287
Processing frame 00288
Processing frame 00289
Processing frame 00290
Processing frame 00291
Processing frame 00292
Processing frame 00293
Processing frame 00294
Processing frame 00295
Processing frame 00296
Processing frame 00297
Processing frame 00298
Processing frame 00299
Processing frame 00300
Processing frame 00301
Processing frame 00302
Processing frame 00303
Processing frame 00304
Processing frame 00305
Processing frame 00306
Processing frame 00307
Processing frame 00308
Processing frame 00309
Processing frame 00310
Processing frame 00311
Processing frame 00312
Processing frame 00313
Processing frame 00314
Processing frame 00315
Processing frame 00316
Processing frame 00317
Processing frame 00318
Processing frame 00319
Processing frame 00320
Processing frame 00321
Processing frame 00322
Processing frame 00323
Processing frame 00324
Processing frame 00325
Processing frame 00326
Processing frame 00327
Processing frame 00328
Processing frame 00329
Processing frame 00330
Processing frame 00331
Processing frame 00332
Processing frame 00333
Processing frame 00334
Processing frame 00335
Processing frame 00336
Processing frame 00337
Processing frame 00338
Processing frame 00339
Processing frame 00340
Processing frame 00341
Processing frame 00342
Processing frame 00343
Processing frame 00344
Processing frame 00345
Processing frame 00346
Processing frame 00347
Processing frame 00348
Processing frame 00349
Processing frame 00350
Processing frame 00351
Processing frame 00352
Processing frame 00353
Processing frame 00354
Processing frame 00355
Processing frame 00356
Processing frame 00357
Processing frame 00358
Processing frame 00359
Processing frame 00360
Processing frame 00361
Processing frame 00362
Processing frame 00363
Processing frame 00364
Processing frame 00365
Processing frame 00366
Processing frame 00367
Processing frame 00368
Processing frame 00369
Processing frame 00370
Processing frame 00371
Processing frame 00372
Processing frame 00373
Processing frame 00374
Processing frame 00375
Processing frame 00376
Processing frame 00377
Processing frame 00378
Processing frame 00379
Processing frame 00380
Processing frame 00381
Processing frame 00382
Processing frame 00383
Processing frame 00384
Processing frame 00385
Processing frame 00386
Processing frame 00387
Processing frame 00388
Processing frame 00389
Processing frame 00390
Processing frame 00391
Processing frame 00392
Processing frame 00393
Processing frame 00394
Processing frame 00395
Processing frame 00396
Processing frame 00397
Processing frame 00398
Processing frame 00399
Processing frame 00400
Processing frame 00401
Processing frame 00402
Processing frame 00403
Processing frame 00404
Processing frame 00405
Processing frame 00406
Processing frame 00407
Processing frame 00408
Processing frame 00409
Processing frame 00410
Processing frame 00411
Processing frame 00412
Processing frame 00413
Processing frame 00414
Processing frame 00415
Processing frame 00416
Processing frame 00417
Processing frame 00418
Processing frame 00419
Processing frame 00420
Processing frame 00421
Processing frame 00422
Processing frame 00423
Processing frame 00424
Processing frame 00425
Processing frame 00426
Processing frame 00427
Processing frame 00428
Processing frame 00429
Processing frame 00430
Processing frame 00431
Processing frame 00432
Processing frame 00433
Processing frame 00434
Processing frame 00435
Processing frame 00436
Processing frame 00437
Processing frame 00438
Processing frame 00439
Processing frame 00440
Processing frame 00441
Processing frame 00442
Processing frame 00443
Processing frame 00444
Processing frame 00445
Processing frame 00446
Processing frame 00447
Processing frame 00448
Processing frame 00449
Processing frame 00450
Processing frame 00451
Processing frame 00452
Processing frame 00453
Processing frame 00454
Processing frame 00455
Processing frame 00456
Processing frame 00457
Processing frame 00458
Processing frame 00459
Processing frame 00460
Processing frame 00461
Processing frame 00462
Processing frame 00463
Processing frame 00464
Processing frame 00465
Processing frame 00466
Processing frame 00467
Processing frame 00468
Processing frame 00469
Processing frame 00470
Processing frame 00471

In [7]:
# Этап 2: TrackEval HOTA на baseline results
!pip install -q "trackeval==1.3.0"

!python scripts/run_eval.py

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.3/80.3 kB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.7/207.7 kB 13.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 113.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 94.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.5.0 which is incompatible.

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 4 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating original

1 eval_sequence(KITTI-17, original)                                      0.1002 sec
2 eval_sequence(PETS09-S2L1, original)                                   0.4557 sec
3 eval_sequence(TUD-Campus, original)                                    0.0434 sec
4 eval_sequence(TUD-Stadtmitte, original)                                0.1218 sec

All sequences for original finished in 0.72 seconds

HOTA: original-pedestrian          HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
KITTI-17                           43.408    43.259    43.809    45.873    68.71     46.103    71.635    75.147    44.78     64.662    67.793    43.837
PETS09-S2L1                        44.841    52.214    38.656    67.839    57.227    45.127    59.885    75.814    51.172    66.056    69.432    45.864
TUD-Campus                         39.864    43.26     37.114    47.31     66.867    40.622    69.111    75.997    41.841    58.592    67.249    39.403
TUD-Stadtmitte                     36.746    43.747    31.106    51.125    55.755    40.741    44.375    71.688    39.809    62.846    59.575    37.441
COMBINED                           43.321    49.538    38.132    61.592    58.093    44.741    59.434    74.98     48.409    65.099    67.6      44.007

CLEAR: original-pedestrian         MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
KITTI-17                           53.734    70.799    54.758    60.761    91.009    0         100       0         35.99     415       268       41        7         0         9         0         14
PETS09-S2L1                        60.97     71.676    63.315    90.929    76.706    89.474    10.526    0         35.215    4070      406       1236      105       17        2         0         100
TUD-Campus                         49.861    71.498    52.925    61.838    87.402    12.5      87.5      0         32.235    222       137       32        11        1         7         0         18
TUD-Stadtmitte                     51.384    65.674    52.768    72.232    78.774    50        50        0         26.59     835       321       225       16        5         5         0         23
COMBINED                           57.971    70.699    60.054    83.039    78.321    50        50        0         33.64     5542      1132      1534      139       23        23        0         155

Identity: original-pedestrian      IDF1      IDR       IDP       IDTP      IDFN      IDFP
KITTI-17                           68.481    57.101    85.526    390       293       66
PETS09-S2L1                        60.049    65.617    55.352    2937      1539      2369
TUD-Campus                         56.117    47.911    67.717    172       187       82
TUD-Stadtmitte                     53.7      51.471    56.132    595       561       465
COMBINED                           59.549    61.343    57.858    4094      2580      2982

Count: original-pedestrian         Dets      GT_Dets   IDs       GT_IDs
KITTI-17                           456       683       13        9
PETS09-S2L1                        5306      4476      64        19
TUD-Campus                         254       359       12        8
TUD-Stadtmitte                     1060      1156      21        10
COMBINED                           7076      6674      110       46

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 2 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating original

5 eval_sequence(MOT16-09, original)                                      0.4165 sec
6 eval_sequence(MOT16-11, original)                                      0.6410 sec

All sequences for original finished in 1.06 seconds

HOTA: original-pedestrian          HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
MOT16-09                           36.241    36.965    35.625    39.372    71.495    37.332    74.577    78.701    37.441    48.759    73.013    35.6
MOT16-11                           39.949    38.42     41.57     40.575    76.169    46.274    74.453    82.049    41.053    50.684    78.572    39.824
COMBINED                           38.651    37.854    39.521    40.137    74.43     43.19     74.705    80.828    39.819    49.994    76.489    38.24

CLEAR: original-pedestrian         MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
MOT16-09                           45.806    75.366    46.547    50.808    92.263    16        68        16        33.29     2671      2586      224       39        4         17        4         122
MOT16-11                           46.654    79.57     46.882    50.076    94.005    7.2464    39.13     53.623    36.423    4594      4580      293       21        5         27        37        69
COMBINED                           46.345    78.024    46.76     50.343    93.356    9.5745    46.809    43.617    35.281    7265      7166      517       60        9         44        41        191

Identity: original-pedestrian      IDF1      IDR       IDP       IDTP      IDFN      IDFP
MOT16-09                           50.294    38.996    70.812    2050      3207      845
MOT16-11                           50.85     38.969    73.153    3575      5599      1312
COMBINED                           50.646    38.979    72.282    5625      8806      2157

Count: original-pedestrian         Dets      GT_Dets   IDs       GT_IDs
MOT16-09                           2895      5257      46        25
MOT16-11                           4887      9174      66        69
COMBINED                           7782      14431     112       94

=== HOTA summary (TrackEval) ===

Tracker: original
Sequence                 HOTA     MOTA     IDF1
------------------------------------------------
KITTI-17                43.41    53.73    68.48
MOT16-09                36.24    45.81    50.29
MOT16-11                39.95    46.65    50.85
PETS09-S2L1             44.84    60.97    60.05
TUD-Campus              39.86    49.86    56.12
TUD-Stadtmitte          36.75    51.38    53.70
------------------------------------------------
MEAN (6 videos)         40.17

Saved: {'csv': 'results/eval/summary.csv', 'json': 'results/eval/summary.json'}

## Detector F1 (YOLO + NanoDet + MMDet)

Сравнение детекций с GT: Precision / Recall / F1 для **всех трёх** детекторов.  
Сначала smoke test (`--max-frames 30`), потом полный прогон без флага.

In [8]:
!python scripts/setup_detectors_colab.py
# веса NanoDet + RTMDet (если ещё нет в resources/models/)
!python scripts/download_detector_models.py

# Полный прогон: Precision / Recall / F1 + FPS по всем 6 видео.
!python scripts/run_detector_eval.py --detector yolo nanodet mmdet

> /usr/bin/python3 -m pip install -q ultralytics scikit-learn
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.3/41.3 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 29.9 MB/s eta 0:00:00
> git clone -b v1.0.0-alpha-1 --depth 1 https://github.com/RangiLyu/nanodet.git /content/DeepSORT_Project_CV/third_party/nanodet
Cloning into '/content/DeepSORT_Project_CV/third_party/nanodet'...
remote: Enumerating objects: 312, done.
remote: Counting objects: 100% (312/312), done.
remote: Compressing objects: 100% (279/279), done.
remote: Total 312 (delta 48), reused 158 (delta 10), pack-reused 0 (from 0)
Receiving objects: 100% (312/312), 1.40 MiB | 4.67 MiB/s, done.
Resolving deltas: 100% (48/48), done.
Note: switching to '08bad3294608953b1e1a8aacc50f67336420a435'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

Patched nanodet/data/collate.py for PyTorch 2.x
Patched nanodet/util/logger.py for pytorch-lightning 2.x
Patched nanodet/model/arch/one_stage_detector.py for CPU inference
> /usr/bin/python3 -m pip install -q -r /content/DeepSORT_Project_CV/third_party/nanodet/requirements.txt
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 97.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 852.4/852.4 kB 57.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 983.4/983.4 kB 66.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.9/2.9 MB 102.4 MB/s eta 0:00:00
  Building wheel for onnx-simplifier (pyproject.toml) ... done
> /usr/bin/python3 -m pip install -q -e /content/DeepSORT_Project_CV/third_party/nanodet
  Preparing metadata (setup.py) ... done
> /usr/bin/python3 -c import nanodet
> /usr/bin/python3 -c from nanodet.data.batch_process import stack_batch_img; from nanodet.model.arch import build_model; from nanodet.util import Logger, load_model_weight
nanodet OK (v1.0.0-alpha-1)
Colab PyTorch 2.11.0+cu128 has no mmcv wheel; pinning torch==2.4.0 ...
> /usr/bin/python3 -m pip install -q --timeout 300 --force-reinstall torch==2.4.0 torchvision==0.19.0 --index-url https://download.pytorch.org/whl/cu121
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 799.0/799.0 MB 1.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 97.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 79.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 51.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 73.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 8.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 14.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 8.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 6.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.2/176.2 MB 7.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 10.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.5/209.5 MB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.1/7.1 MB 75.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.6/44.6 kB 4.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.4/203.4 kB 18.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.9/134.9 kB 14.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 79.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 95.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 930.8/930.8 kB 60.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 124.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 41.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.7/39.7 MB 17.9 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
datasets 4.0.0 requires fsspec[http]<=2025.3.0,>=2023.1.0, but you have fsspec 2026.4.0 which is incompatible.
gradio 5.50.0 requires pillow<12.0,>=8.0, but you have pillow 12.2.0 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.4.4 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2026.4.0 which is incompatible.
PyTorch 2.4.0+cu121 ready for mmcv (cu121/torch2.4.0)
> /usr/bin/python3 -m pip install -q --timeout 300 setuptools==75.8.2 openmim mmengine
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.8/46.8 kB 2.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.5/259.5 kB 11.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 42.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.7/52.7 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 452.7/452.7 kB 45.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 256.2/256.2 kB 29.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.3/55.3 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 93.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
Installing mmcv==2.2.0 from prebuilt wheel (cu121/torch2.4.0) ...
> /usr/bin/python3 -m pip install -q --timeout 300 mmcv==2.2.0 -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.4.0/index.html --only-binary mmcv
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 MB 7.4 MB/s eta 0:00:00
> /usr/bin/python3 -m pip install -q --timeout 300 mmdet==3.3.0
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 42.4 MB/s eta 0:00:00
Patched /usr/local/lib/python3.12/dist-packages/mmdet/__init__.py for mmcv==2.2.0
> /usr/bin/python3 -c import mmdet
mmdet OK (mmcv==2.2.0, cu121/torch2.4.0)
Detector deps ready.
OK (exists): /content/DeepSORT_Project_CV/resources/models/nanodet/nanodet-plus-m_416.yml
OK (exists): /content/DeepSORT_Project_CV/resources/models/nanodet/nanodet-plus-m_416_checkpoint.ckpt
OK (exists): /content/DeepSORT_Project_CV/resources/models/mmdet/rtmdet/rtmdet_tiny_8xb32-300e_coco.py
OK (exists): /content/DeepSORT_Project_CV/resources/models/mmdet/rtmdet/rtmdet_s_8xb32-300e_coco.py
OK (exists): /content/DeepSORT_Project_CV/resources/models/mmdet/rtmdet/rtmdet_l_8xb32-300e_coco.py
OK (exists): /content/DeepSORT_Project_CV/resources/models/mmdet/rtmdet/rtmdet_tta.py
OK (exists): /content/DeepSORT_Project_CV/resources/models/mmdet/_base_/default_runtime.py
OK (exists): /content/DeepSORT_Project_CV/resources/models/mmdet/_base_/schedules/schedule_1x.py
OK (exists): /content/DeepSORT_Project_CV/resources/models/mmdet/_base_/datasets/coco_detection.py
OK (exists): /content/DeepSORT_Project_CV/resources/models/mmdet/rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth
Done. Weights under resources/models/

Loading detector: yolo
Creating new Ultralytics Settings v0.0.6 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Downloading https://github.com/ultralytics/assets/releases/download/v8.4.0/yolov8n.pt to 'yolov8n.pt': 100% ━━━━━━━━━━━━ 6.2MB 106.9MB/s 0.1s
Evaluating yolo on 6 sequences ...
  TUD-Campus ...
  TUD-Stadtmitte ...
  KITTI-17 ...
  PETS09-S2L1 ...
  MOT16-09 ...
  MOT16-11 ...

Loading detector: nanodet
model size is  1.0x
init weights...
Downloading: "https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth" to /root/.cache/torch/hub/checkpoints/shufflenetv2_x1-5666bf0f80.pth
100% 8.79M/8.79M [00:00<00:00, 147MB/s]
=> loading pretrained model https://download.pytorch.org/models/shufflenetv2_x1-5666bf0f80.pth
Finish initialize NanoDet-Plus Head.
/content/DeepSORT_Project_CV/detectors/nanodet.py:50: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(checkpoint, map_location=lambda storage, loc: storage)
Evaluating nanodet on 6 sequences ...
  TUD-Campus ...
/usr/local/lib/python3.12/dist-packages/torch/functional.py:513: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3609.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  TUD-Stadtmitte ...
  KITTI-17 ...
  PETS09-S2L1 ...
  MOT16-09 ...
  MOT16-11 ...

Loading detector: mmdet
/usr/local/lib/python3.12/dist-packages/mmengine/optim/optimizer/zero_optimizer.py:11: DeprecationWarning: `TorchScript` support for functional optimizers is deprecated and will be removed in a future PyTorch release. Consider using the `torch.compile` optimizer instead.
  from torch.distributed.optim import \
Loads checkpoint by local backend from path: resources/models/mmdet/rtmdet_tiny_8xb32-300e_coco_20220902_112414-78e30dcc.pth
/usr/local/lib/python3.12/dist-packages/mmengine/runner/checkpoint.py:347: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(filename, map_location=map_location)
The model and loaded state dict do not match exactly

unexpected key in source state_dict: data_preprocessor.mean, data_preprocessor.std

Evaluating mmdet on 6 sequences ...
  TUD-Campus ...
/usr/local/lib/python3.12/dist-packages/mmdet/models/layers/se_layer.py:158: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=False):
/usr/local/lib/python3.12/dist-packages/mmdet/models/backbones/csp_darknet.py:118: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=False):
  TUD-Stadtmitte ...
  KITTI-17 ...
  PETS09-S2L1 ...
  MOT16-09 ...
  MOT16-11 ...

=== Detector F1 summary ===

Detector: yolo
Sequence                 Prec   Recall       F1      FPS
---------------------------------------------------------
KITTI-17                0.834    0.840    0.837    90.30
MOT16-09                0.760    0.822    0.790    79.26
MOT16-11                0.842    0.705    0.767    82.61
PETS09-S2L1             0.875    0.924    0.899    85.57
TUD-Campus              0.684    0.858    0.761    92.70
TUD-Stadtmitte          0.934    0.850    0.890    83.22
---------------------------------------------------------
MEAN (6 videos)                           0.824    85.61

Detector: nanodet
Sequence                 Prec   Recall       F1      FPS
---------------------------------------------------------
KITTI-17                0.453    0.840    0.589    38.48
MOT16-09                0.501    0.818    0.621    35.13
MOT16-11                0.620    0.699    0.658    35.46
PETS09-S2L1             0.682    0.934    0.788    34.14
TUD-Campus              0.470    0.808    0.594    38.84
TUD-Stadtmitte          0.657    0.848    0.740    32.83
---------------------------------------------------------
MEAN (6 videos)                           0.665    35.81

Detector: mmdet
Sequence                 Prec   Recall       F1      FPS
---------------------------------------------------------
KITTI-17                0.565    0.876    0.687    11.01
MOT16-09                0.562    0.870    0.683    10.68
MOT16-11                0.688    0.740    0.713    10.81
PETS09-S2L1             0.751    0.940    0.835    10.71
TUD-Campus              0.412    0.883    0.562    10.83
TUD-Stadtmitte          0.820    0.873    0.845    10.64
---------------------------------------------------------
MEAN (6 videos)                           0.721    10.78

Saved: {'csv': 'results/detectors/summary.csv', 'json': 'results/detectors/summary.json'}

## ReID clustering metrics (4 models, 2 sources)

Standalone-оценка на **GT pedestrian crops**: Silhouette, Calinski–Harabasz, Fowlkes–Mallows.

| Модель | Источник |
|--------|----------|
| `osnet`, `resnet50` | torchreid |
| `resnet50_ibn`, `fastreid` | fast-reid |

Сначала smoke test (`--max-frames 30 --max-samples 500`), потом полный прогон.

In [9]:
!git pull
!python scripts/setup_reid_colab.py
!python scripts/download_reid_models.py

# smoke test — все 4 ReID модели (2 источника)
!python scripts/run_reid_eval.py --model osnet resnet50 resnet50_ibn fastreid --max-frames 30 --max-samples 500

# полный прогон
!python scripts/run_reid_eval.py --model osnet resnet50 resnet50_ibn fastreid

Already up to date.
> /usr/bin/python3 -m pip install -q --timeout 300 scikit-learn tabulate termcolor yacs prettytable easydict
> /usr/bin/python3 -m pip install -q --timeout 300 Cython h5py Pillow six scipy opencv-python matplotlib future yacs gdown imageio chardet
> /usr/bin/python3 -m pip install -q --timeout 300 --no-deps git+https://github.com/KaiyangZhou/deep-person-reid.git
  Preparing metadata (setup.py) ... done
  Building wheel for torchreid (setup.py) ... done
> /usr/bin/python3 -c import torchreid
> git clone --depth 1 --branch v1.3.0 https://github.com/JDAI-CV/fast-reid.git /content/DeepSORT_Project_CV/third_party/fast_reid
Cloning into '/content/DeepSORT_Project_CV/third_party/fast_reid'...
remote: Enumerating objects: 536, done.
remote: Counting objects: 100% (536/536), done.
remote: Compressing objects: 100% (447/447), done.
remote: Total 536 (delta 109), reused 234 (delta 68), pack-reused 0 (from 0)
Receiving objects: 100% (536/536), 2.15 MiB | 6.51 MiB/s, done.
Resolving deltas: 100% (109/109), done.
Note: switching to '54f96ba78ad087c7110bafe2132a91536f0b5a01'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

> /usr/bin/python3 -c import sys; sys.path.insert(0, '/content/DeepSORT_Project_CV/third_party/fast_reid'); import fastreid; print('fastreid OK')
fastreid OK
mmcv detected — repairing torch/mmcv compatibility for MMDet ...
> /usr/bin/python3 /content/DeepSORT_Project_CV/scripts/setup_detectors_colab.py --repair-mmcv-only
PyTorch 2.4.0+cu121 ready for mmcv (cu121/torch2.4.0)
Reinstalling mmcv==2.2.0 for torch 2.4.0 (cu121) ...
> /usr/bin/python3 -m pip install -q --timeout 300 --force-reinstall mmcv==2.2.0 -f https://download.openmmlab.com/mmcv/dist/cu121/torch2.4.0/index.html --only-binary mmcv
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 118.7/118.7 kB 432.4 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.9/72.9 MB 15.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.2/100.2 kB 10.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 807.9/807.9 kB 58.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.7/310.7 kB 19.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 362.6/362.6 kB 36.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 131.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 81.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.7/91.7 kB 9.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 77.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.8/122.8 kB 14.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 24.5 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchreid 1.4.0 requires flake8, which is not installed.
torchreid 1.4.0 requires isort==4.3.21, which is not installed.
torchreid 1.4.0 requires tb-nightly, which is not installed.
ipython 7.34.0 requires jedi>=0.16, which is not installed.
datasets 4.0.0 requires fsspec[http]<=2025.3.0,>=2023.1.0, but you have fsspec 2026.4.0 which is incompatible.
gradio 5.50.0 requires pillow<12.0,>=8.0, but you have pillow 12.2.0 which is incompatible.
numba 0.60.0 requires numpy<2.1,>=1.22, but you have numpy 2.5.0 which is incompatible.
bigframes 2.42.0 requires rich<14,>=12.4.4, but you have rich 15.0.0 which is incompatible.
pyiceberg 0.11.1 requires rich<15.0.0,>=10.11.0, but you have rich 15.0.0 which is incompatible.
Already patched: /usr/local/lib/python3.12/dist-packages/mmdet/__init__.py
> /usr/bin/python3 -c import mmcv
> /usr/bin/python3 -c import mmdet
mmcv/mmdet import OK after repair.

ReID setup OK: torchreid + fastreid (sys.path, no pip install)
OK (exists): /content/DeepSORT_Project_CV/resources/models/fastreid/market_bot_R50.pth
Downloading https://github.com/JDAI-CV/fast-reid/releases/download/v0.1.1/market_bot_R50-ibn.pth -> /content/DeepSORT_Project_CV/resources/models/fastreid/market_bot_R50-ibn.pth
Downloading Google Drive 1dUUZ4rHDWohmsQXCRe2C_HbYkzz94iBV -> /content/DeepSORT_Project_CV/resources/models/torchreid/market1501_resnet50.pth
Downloading...
From: https://drive.google.com/uc?id=1dUUZ4rHDWohmsQXCRe2C_HbYkzz94iBV
To: /content/DeepSORT_Project_CV/resources/models/torchreid/market1501_resnet50.pth
100% 100M/100M [00:01<00:00, 58.0MB/s]
Done. osnet (torchreid) downloads weights on first run; resnet50 uses resources/models/torchreid/market1501_resnet50.pth; resnet50_ibn/fastreid use fast-reid checkpoints.

Loading ReID model: osnet
Downloading...
From: https://drive.google.com/uc?id=1LaG1EJpHrxdAxKnSCJ_i0u-nbxSAeiFY
To: /root/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth
100% 10.9M/10.9M [00:00<00:00, 55.7MB/s]
/usr/local/lib/python3.12/dist-packages/torchreid/models/osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)
Successfully loaded imagenet pretrained weights from "/root/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
Evaluating osnet on 6 sequences ...
  TUD-Campus ...
  TUD-Stadtmitte ...
  KITTI-17 ...
  PETS09-S2L1 ...
  MOT16-09 ...
  MOT16-11 ...

Loading ReID model: resnet50
/usr/local/lib/python3.12/dist-packages/torchreid/utils/torchtools.py:85: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fpath, map_location=map_location)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torchreid/utils/torchtools.py", line 85, in load_checkpoint
    checkpoint = torch.load(fpath, map_location=map_location)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/serialization.py", line 1114, in load
    return _legacy_load(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/serialization.py", line 1348, in _legacy_load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/DeepSORT_Project_CV/scripts/run_reid_eval.py", line 131, in <module>
    main()
  File "/content/DeepSORT_Project_CV/scripts/run_reid_eval.py", line 110, in main
    extractor = create_reid_extractor(name, reid_cfg["reid_models"][name])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/DeepSORT_Project_CV/reid/base.py", line 124, in create_reid_extractor
    return TorchReIDExtractor(model_name=model_name, **cfg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/DeepSORT_Project_CV/reid/torchreid_ext.py", line 59, in __init__
    self.model = _build_torchreid_model(model_name, checkpoint)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/DeepSORT_Project_CV/reid/torchreid_ext.py", line 41, in _build_torchreid_model
    load_pretrained_weights(model, checkpoint)
  File "/usr/local/lib/python3.12/dist-packages/torchreid/utils/torchtools.py", line 273, in load_pretrained_weights
    checkpoint = load_checkpoint(weight_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torchreid/utils/torchtools.py", line 89, in load_checkpoint
    checkpoint = torch.load(
                 ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/serialization.py", line 1114, in load
    return _legacy_load(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/serialization.py", line 1141, in _legacy_load
    class UnpicklerWrapper(pickle_module.Unpickler):  # type: ignore[name-defined]
TypeError: the first argument must be callable

Loading ReID model: osnet
/usr/local/lib/python3.12/dist-packages/torchreid/models/osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)
Successfully loaded imagenet pretrained weights from "/root/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
Evaluating osnet on 6 sequences ...
  TUD-Campus ...
  TUD-Stadtmitte ...
  KITTI-17 ...
  PETS09-S2L1 ...
  MOT16-09 ...
  MOT16-11 ...

Loading ReID model: resnet50
/usr/local/lib/python3.12/dist-packages/torchreid/utils/torchtools.py:85: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(fpath, map_location=map_location)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/torchreid/utils/torchtools.py", line 85, in load_checkpoint
    checkpoint = torch.load(fpath, map_location=map_location)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/serialization.py", line 1114, in load
    return _legacy_load(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/serialization.py", line 1348, in _legacy_load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x83 in position 2: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/content/DeepSORT_Project_CV/scripts/run_reid_eval.py", line 131, in <module>
    main()
  File "/content/DeepSORT_Project_CV/scripts/run_reid_eval.py", line 110, in main
    extractor = create_reid_extractor(name, reid_cfg["reid_models"][name])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/DeepSORT_Project_CV/reid/base.py", line 124, in create_reid_extractor
    return TorchReIDExtractor(model_name=model_name, **cfg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/DeepSORT_Project_CV/reid/torchreid_ext.py", line 59, in __init__
    self.model = _build_torchreid_model(model_name, checkpoint)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/DeepSORT_Project_CV/reid/torchreid_ext.py", line 41, in _build_torchreid_model
    load_pretrained_weights(model, checkpoint)
  File "/usr/local/lib/python3.12/dist-packages/torchreid/utils/torchtools.py", line 273, in load_pretrained_weights
    checkpoint = load_checkpoint(weight_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torchreid/utils/torchtools.py", line 89, in load_checkpoint
    checkpoint = torch.load(
                 ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/serialization.py", line 1114, in load
    return _legacy_load(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/torch/serialization.py", line 1141, in _legacy_load
    class UnpicklerWrapper(pickle_module.Unpickler):  # type: ignore[name-defined]
TypeError: the first argument must be callable

## Модифицированный DeepSORT (детектор + ReID) → HOTA

Live-пайплайн: детектор → ReID-дескрипторы → ядро DeepSORT (Kalman + matching cascade) → MOT-txt.

In [10]:
NAME = "yolo_osnet"
# Прогон трекера по 6 видео (печатает FPS по каждому).
!python scripts/run_tracker.py --detector yolo --reid osnet --tracker-name {NAME}

# HOTA модифицированного трекера
!python scripts/run_eval.py --tracker-name {NAME} --results-dir results/tracking/{NAME}

Detector: yolo | ReID: osnet | mask_background: False | identity: False | tracker_name: yolo_osnet
/usr/local/lib/python3.12/dist-packages/torchreid/models/osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)
Successfully loaded imagenet pretrained weights from "/root/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

Tracking TUD-Campus ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  TUD-Campus: 20.10 FPS (det 12.0ms | reid 33.1ms | track 4.7ms)

Tracking TUD-Stadtmitte ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  TUD-Stadtmitte: 16.76 FPS (det 15.0ms | reid 37.5ms | track 7.1ms)

Tracking KITTI-17 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  KITTI-17: 16.42 FPS (det 16.1ms | reid 38.0ms | track 6.8ms)

Tracking PETS09-S2L1 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  PETS09-S2L1: 16.85 FPS (det 15.9ms | reid 35.9ms | track 7.6ms)

Tracking MOT16-09 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  MOT16-09: 14.21 FPS (det 16.0ms | reid 42.3ms | track 12.0ms)

Tracking MOT16-11 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  MOT16-11: 15.31 FPS (det 16.3ms | reid 39.8ms | track 9.2ms)

=== Tracking FPS summary ===
Sequence                  FPS   det ms  reid ms  track ms
--------------------------------------------------------
KITTI-17                16.42     16.1     38.0       6.8
MOT16-09                14.21     16.0     42.3      12.0
MOT16-11                15.31     16.3     39.8       9.2
PETS09-S2L1             16.85     15.9     35.9       7.6
TUD-Campus              20.10     12.0     33.1       4.7
TUD-Stadtmitte          16.76     15.0     37.5       7.1
--------------------------------------------------------
MEAN                    16.61

Results: /content/DeepSORT_Project_CV/results/tracking/yolo_osnet
Evaluate: python scripts/run_eval.py --tracker-name yolo_osnet --results-dir /content/DeepSORT_Project_CV/results/tracking/yolo_osnet

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 4 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_osnet

1 eval_sequence(KITTI-17, yolo_osnet)                                    0.0860 sec
2 eval_sequence(PETS09-S2L1, yolo_osnet)                                 0.4628 sec
3 eval_sequence(TUD-Campus, yolo_osnet)                                  0.0451 sec
4 eval_sequence(TUD-Stadtmitte, yolo_osnet)                              0.1228 sec

All sequences for yolo_osnet finished in 0.72 seconds

HOTA: yolo_osnet-pedestrian        HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
KITTI-17                           55.708    56.522    54.955    65.724    68.638    59.582    74.801    79.826    60.073    76.311    74.929    57.179
PETS09-S2L1                        52.427    63.524    43.374    73.212    70.396    55.692    61.184    80.032    56.334    71.257    75.452    53.765
TUD-Campus                         47.956    47.445    48.649    66.046    55.269    60.149    63.451    79.583    56.67     65.199    73.903    48.184
TUD-Stadtmitte                     55.113    60.653    50.175    66.878    73.981    63.936    61.676    80.957    57.917    72.981    76.716    55.988
COMBINED                           52.957    61.277    45.87     70.963    69.822    57.658    62.703    80.143    57.04     71.707    75.525    54.157

CLEAR: yolo_osnet-pedestrian       MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
KITTI-17                           65.154    77.057    66.471    81.113    84.709    55.556    44.444    0         46.544    554       129       100       9         5         4         0         11
PETS09-S2L1                        79.893    76.656    80.451    92.225    88.679    84.211    15.789    0         58.363    4128      348       527       25        16        3         0         86
TUD-Campus                         47.354    75.926    48.189    83.844    70.163    50        50        0         27.169    301       58        128       3         4         4         0         7
TUD-Stadtmitte                     74.913    77.788    75.346    82.872    91.675    70        30        0         56.506    958       198       87        5         7         3         0         10
COMBINED                           75.772    76.839    76.401    89.017    87.587    69.565    30.435    0         55.154    5941      733       842       42        32        14        0         114

Identity: yolo_osnet-pedestrian    IDF1      IDR       IDP       IDTP      IDFN      IDFP
KITTI-17                           75.093    73.499    76.758    502       181       152
PETS09-S2L1                        66.433    67.761    65.156    3033      1443      1622
TUD-Campus                         68.528    75.209    62.937    270       89        159
TUD-Stadtmitte                     69.332    66.003    73.014    763       393       282
COMBINED                           67.89     68.445    67.345    4568      2106      2215

Count: yolo_osnet-pedestrian       Dets      GT_Dets   IDs       GT_IDs
KITTI-17                           654       683       13        9
PETS09-S2L1                        4655      4476      30        19
TUD-Campus                         429       359       12        8
TUD-Stadtmitte                     1045      1156      12        10
COMBINED                           6783      6674      67        46

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 2 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_osnet

5 eval_sequence(MOT16-09, yolo_osnet)                                    0.4215 sec
6 eval_sequence(MOT16-11, yolo_osnet)                                    0.7076 sec

All sequences for yolo_osnet finished in 1.13 seconds

HOTA: yolo_osnet-pedestrian        HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
MOT16-09                           44.232    50.56     39.019    56.472    73.429    43.93     68.924    82.155    46.889    57.365    76.229    43.729
MOT16-11                           51.95     50.007    54.321    55.154    76.861    59.683    82.11     84.473    54.69     65.045    79.386    51.636
COMBINED                           49.267    50.191    48.79     55.634    75.555    54.058    77.418    83.612    52.026    62.348    78.187    48.748

CLEAR: yolo_osnet-pedestrian       MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
MOT16-09                           57.409    80.159    58.798    67.852    88.227    40        48        12        43.946    3567      1690      476       73        10        12        3         87
MOT16-11                           53.041    83.303    53.314    62.535    87.149    24.638    33.333    42.029    42.6      5737      3437      846       25        17        23        29        50
COMBINED                           54.632    82.098    55.311    64.472    87.559    28.723    37.234    34.043    43.09     9304      5127      1322      98        27        35        32        137

Identity: yolo_osnet-pedestrian    IDF1      IDR       IDP       IDTP      IDFN      IDFP
MOT16-09                           55.161    48.792    63.443    2565      2692      1478
MOT16-11                           60.595    52.038    72.52     4774      4400      1809
COMBINED                           58.578    50.856    69.066    7339      7092      3287

Count: yolo_osnet-pedestrian       Dets      GT_Dets   IDs       GT_IDs
MOT16-09                           4043      5257      53        25
MOT16-11                           6583      9174      87        69
COMBINED                           10626     14431     140       94

=== HOTA summary (TrackEval) ===

Tracker: yolo_osnet
Sequence                 HOTA     MOTA     IDF1
------------------------------------------------
KITTI-17                55.71    65.15    75.09
MOT16-09                44.23    57.41    55.16
MOT16-11                51.95    53.04    60.60
PETS09-S2L1             52.43    79.89    66.43
TUD-Campus              47.96    47.35    68.53
TUD-Stadtmitte          55.11    74.91    69.33
------------------------------------------------
MEAN (6 videos)         51.23

Saved: {'csv': 'results/eval/summary.csv', 'json': 'results/eval/summary.json'}

## Перебор связок (detector × ReID) → сводная таблица

Несколько комбинаций, где считается HOTA по каждому видео + средний FPS, сравнивает с baseline и отмечает лучшую real-time связку (≥5 FPS)

In [11]:
!python scripts/run_sweep.py --combos yolo:osnet yolo:resnet50_ibn nanodet:osnet mmdet:osnet yolo_seg:osnet:seg

import pandas as pd
pd.read_csv("results/tracking/sweep_summary.csv")

Evaluating baseline (original) ...

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 4 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating original

1 eval_sequence(KITTI-17, original)                                      0.0920 sec
2 eval_sequence(PETS09-S2L1, original)                                   0.6178 sec
3 eval_sequence(TUD-Campus, original)                                    0.0956 sec
4 eval_sequence(TUD-Stadtmitte, original)                                0.2173 sec

All sequences for original finished in 1.02 seconds

HOTA: original-pedestrian          HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
KITTI-17                           43.408    43.259    43.809    45.873    68.71     46.103    71.635    75.147    44.78     64.662    67.793    43.837
PETS09-S2L1                        44.841    52.214    38.656    67.839    57.227    45.127    59.885    75.814    51.172    66.056    69.432    45.864
TUD-Campus                         39.864    43.26     37.114    47.31     66.867    40.622    69.111    75.997    41.841    58.592    67.249    39.403
TUD-Stadtmitte                     36.746    43.747    31.106    51.125    55.755    40.741    44.375    71.688    39.809    62.846    59.575    37.441
COMBINED                           43.321    49.538    38.132    61.592    58.093    44.741    59.434    74.98     48.409    65.099    67.6      44.007

CLEAR: original-pedestrian         MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
KITTI-17                           53.734    70.799    54.758    60.761    91.009    0         100       0         35.99     415       268       41        7         0         9         0         14
PETS09-S2L1                        60.97     71.676    63.315    90.929    76.706    89.474    10.526    0         35.215    4070      406       1236      105       17        2         0         100
TUD-Campus                         49.861    71.498    52.925    61.838    87.402    12.5      87.5      0         32.235    222       137       32        11        1         7         0         18
TUD-Stadtmitte                     51.384    65.674    52.768    72.232    78.774    50        50        0         26.59     835       321       225       16        5         5         0         23
COMBINED                           57.971    70.699    60.054    83.039    78.321    50        50        0         33.64     5542      1132      1534      139       23        23        0         155

Identity: original-pedestrian      IDF1      IDR       IDP       IDTP      IDFN      IDFP
KITTI-17                           68.481    57.101    85.526    390       293       66
PETS09-S2L1                        60.049    65.617    55.352    2937      1539      2369
TUD-Campus                         56.117    47.911    67.717    172       187       82
TUD-Stadtmitte                     53.7      51.471    56.132    595       561       465
COMBINED                           59.549    61.343    57.858    4094      2580      2982

Count: original-pedestrian         Dets      GT_Dets   IDs       GT_IDs
KITTI-17                           456       683       13        9
PETS09-S2L1                        5306      4476      64        19
TUD-Campus                         254       359       12        8
TUD-Stadtmitte                     1060      1156      21        10
COMBINED                           7076      6674      110       46

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 2 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating original

5 eval_sequence(MOT16-09, original)                                      1.0015 sec
6 eval_sequence(MOT16-11, original)                                      2.7198 sec

All sequences for original finished in 3.72 seconds

HOTA: original-pedestrian          HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
MOT16-09                           36.241    36.965    35.625    39.372    71.495    37.332    74.577    78.701    37.441    48.759    73.013    35.6
MOT16-11                           39.949    38.42     41.57     40.575    76.169    46.274    74.453    82.049    41.053    50.684    78.572    39.824
COMBINED                           38.651    37.854    39.521    40.137    74.43     43.19     74.705    80.828    39.819    49.994    76.489    38.24

CLEAR: original-pedestrian         MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
MOT16-09                           45.806    75.366    46.547    50.808    92.263    16        68        16        33.29     2671      2586      224       39        4         17        4         122
MOT16-11                           46.654    79.57     46.882    50.076    94.005    7.2464    39.13     53.623    36.423    4594      4580      293       21        5         27        37        69
COMBINED                           46.345    78.024    46.76     50.343    93.356    9.5745    46.809    43.617    35.281    7265      7166      517       60        9         44        41        191

Identity: original-pedestrian      IDF1      IDR       IDP       IDTP      IDFN      IDFP
MOT16-09                           50.294    38.996    70.812    2050      3207      845
MOT16-11                           50.85     38.969    73.153    3575      5599      1312
COMBINED                           50.646    38.979    72.282    5625      8806      2157

Count: original-pedestrian         Dets      GT_Dets   IDs       GT_IDs
MOT16-09                           2895      5257      46        25
MOT16-11                           4887      9174      66        69
COMBINED                           7782      14431     112       94

=== Combo: yolo + osnet ===
/usr/local/lib/python3.12/dist-packages/torchreid/models/osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)
Successfully loaded imagenet pretrained weights from "/root/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
  TUD-Campus: 11.62 FPS
  TUD-Stadtmitte: 17.59 FPS
  KITTI-17: 21.81 FPS
  PETS09-S2L1: 16.82 FPS
  MOT16-09: 13.60 FPS
  MOT16-11: 14.71 FPS

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 4 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_osnet

7 eval_sequence(KITTI-17, yolo_osnet)                                    0.1458 sec
8 eval_sequence(PETS09-S2L1, yolo_osnet)                                 0.4939 sec
9 eval_sequence(TUD-Campus, yolo_osnet)                                  0.0480 sec
10 eval_sequence(TUD-Stadtmitte, yolo_osnet)                              0.1146 sec

All sequences for yolo_osnet finished in 0.80 seconds

HOTA: yolo_osnet-pedestrian        HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
KITTI-17                           55.708    56.522    54.955    65.724    68.638    59.582    74.801    79.826    60.073    76.311    74.929    57.179
PETS09-S2L1                        52.427    63.524    43.374    73.212    70.396    55.692    61.184    80.032    56.334    71.257    75.452    53.765
TUD-Campus                         47.956    47.445    48.649    66.046    55.269    60.149    63.451    79.583    56.67     65.199    73.903    48.184
TUD-Stadtmitte                     55.113    60.653    50.175    66.878    73.981    63.936    61.676    80.957    57.917    72.981    76.716    55.988
COMBINED                           52.957    61.277    45.87     70.963    69.822    57.658    62.703    80.143    57.04     71.707    75.525    54.157

CLEAR: yolo_osnet-pedestrian       MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
KITTI-17                           65.154    77.057    66.471    81.113    84.709    55.556    44.444    0         46.544    554       129       100       9         5         4         0         11
PETS09-S2L1                        79.893    76.656    80.451    92.225    88.679    84.211    15.789    0         58.363    4128      348       527       25        16        3         0         86
TUD-Campus                         47.354    75.926    48.189    83.844    70.163    50        50        0         27.169    301       58        128       3         4         4         0         7
TUD-Stadtmitte                     74.913    77.788    75.346    82.872    91.675    70        30        0         56.506    958       198       87        5         7         3         0         10
COMBINED                           75.772    76.839    76.401    89.017    87.587    69.565    30.435    0         55.154    5941      733       842       42        32        14        0         114

Identity: yolo_osnet-pedestrian    IDF1      IDR       IDP       IDTP      IDFN      IDFP
KITTI-17                           75.093    73.499    76.758    502       181       152
PETS09-S2L1                        66.433    67.761    65.156    3033      1443      1622
TUD-Campus                         68.528    75.209    62.937    270       89        159
TUD-Stadtmitte                     69.332    66.003    73.014    763       393       282
COMBINED                           67.89     68.445    67.345    4568      2106      2215

Count: yolo_osnet-pedestrian       Dets      GT_Dets   IDs       GT_IDs
KITTI-17                           654       683       13        9
PETS09-S2L1                        4655      4476      30        19
TUD-Campus                         429       359       12        8
TUD-Stadtmitte                     1045      1156      12        10
COMBINED                           6783      6674      67        46

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 2 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_osnet

11 eval_sequence(MOT16-09, yolo_osnet)                                    0.4490 sec
12 eval_sequence(MOT16-11, yolo_osnet)                                    0.7135 sec

All sequences for yolo_osnet finished in 1.16 seconds

HOTA: yolo_osnet-pedestrian        HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
MOT16-09                           44.232    50.56     39.019    56.472    73.429    43.93     68.924    82.155    46.889    57.365    76.229    43.729
MOT16-11                           51.95     50.007    54.321    55.154    76.861    59.683    82.11     84.473    54.69     65.045    79.386    51.636
COMBINED                           49.267    50.191    48.79     55.634    75.555    54.058    77.418    83.612    52.026    62.348    78.187    48.748

CLEAR: yolo_osnet-pedestrian       MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
MOT16-09                           57.409    80.159    58.798    67.852    88.227    40        48        12        43.946    3567      1690      476       73        10        12        3         87
MOT16-11                           53.041    83.303    53.314    62.535    87.149    24.638    33.333    42.029    42.6      5737      3437      846       25        17        23        29        50
COMBINED                           54.632    82.098    55.311    64.472    87.559    28.723    37.234    34.043    43.09     9304      5127      1322      98        27        35        32        137

Identity: yolo_osnet-pedestrian    IDF1      IDR       IDP       IDTP      IDFN      IDFP
MOT16-09                           55.161    48.792    63.443    2565      2692      1478
MOT16-11                           60.595    52.038    72.52     4774      4400      1809
COMBINED                           58.578    50.856    69.066    7339      7092      3287

Count: yolo_osnet-pedestrian       Dets      GT_Dets   IDs       GT_IDs
MOT16-09                           4043      5257      53        25
MOT16-11                           6583      9174      87        69
COMBINED                           10626     14431     140       94

=== Combo: yolo + resnet50_ibn ===
/content/DeepSORT_Project_CV/reid/fastreid_ext.py:32: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(checkpoint_path, map_location="cpu")
  TUD-Campus: 24.83 FPS
  TUD-Stadtmitte: 13.40 FPS
  KITTI-17: 19.33 FPS
  PETS09-S2L1: 11.47 FPS
  MOT16-09: 9.36 FPS
  MOT16-11: 9.45 FPS

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 4 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_resnet50_ibn

13 eval_sequence(KITTI-17, yolo_resnet50_ibn)                             0.1297 sec
14 eval_sequence(PETS09-S2L1, yolo_resnet50_ibn)                          0.4768 sec
15 eval_sequence(TUD-Campus, yolo_resnet50_ibn)                           0.0458 sec
16 eval_sequence(TUD-Stadtmitte, yolo_resnet50_ibn)                       0.1716 sec

All sequences for yolo_resnet50_ibn finished in 0.82 seconds

HOTA: yolo_resnet50_ibn-pedestrian HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
KITTI-17                           57.137    56.411    57.91     66.425    67.917    63.989    73.096    80.125    61.991    78.391    75.205    58.954
PETS09-S2L1                        52.41     63.382    43.441    73.394    70.12     58.705    60.002    80.086    56.444    71.339    75.488    53.853
TUD-Campus                         40.021    47.544    33.946    65.636    55.573    51.187    43.809    79.317    47.151    53.311    73.197    39.022
TUD-Stadtmitte                     53.381    60.274    47.39     66.905    73.241    62.091    60.154    80.736    56.296    70.951    76.186    54.054
COMBINED                           52.394    61.123    45.013    71.139    69.484    59.411    60.502    80.156    56.573    71.038    75.456    53.603

CLEAR: yolo_resnet50_ibn-pedestrianMOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
KITTI-17                           64.129    77.54     65.3      81.552    83.383    55.556    44.444    0         45.812    557       126       111       8         5         4         0         11
PETS09-S2L1                        79.401    76.742    79.96     92.315    88.196    84.211    15.789    0         57.931    4132      344       553       25        16        3         0         81
TUD-Campus                         45.682    75.727    47.354    82.73     70.047    50        50        0         25.601    297       62        127       6         4         4         0         9
TUD-Stadtmitte                     73.529    77.61     74.048    82.699    90.53     60        40        0         55.013    956       200       100       6         6         4         0         10
COMBINED                           75.007    76.906    75.682    89.032    86.96     67.391    32.609    0         54.446    5942      732       891       45        31        15        0         111

Identity: yolo_resnet50_ibn-pedestrianIDF1      IDR       IDP       IDTP      IDFN      IDFP
KITTI-17                           78.905    78.038    79.79     533       150       135
PETS09-S2L1                        66.194    67.739    64.717    3032      1444      1653
TUD-Campus                         49.808    54.318    45.991    195       164       229
TUD-Stadtmitte                     68.987    66.003    72.254    763       393       293
COMBINED                           66.973    67.77     66.193    4523      2151      2310

Count: yolo_resnet50_ibn-pedestrianDets      GT_Dets   IDs       GT_IDs
KITTI-17                           668       683       12        9
PETS09-S2L1                        4685      4476      30        19
TUD-Campus                         424       359       12        8
TUD-Stadtmitte                     1056      1156      11        10
COMBINED                           6833      6674      65        46

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 2 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_resnet50_ibn


,combo,TUD-Campus,TUD-Stadtmitte,KITTI-17,PETS09-S2L1,MOT16-09,MOT16-11,MEAN,mean_fps,beats_all
0,original,39.86,36.75,43.41,44.84,36.24,39.95,40.17,NaN,NaN
1,yolo_osnet,47.96,55.11,55.71,52.43,44.23,51.95,51.23,16.03,True
2,yolo_resnet50_ibn,40.02,53.38,57.14,52.41,38.80,44.48,47.70,14.64,True
3,nanodet_osnet,38.85,46.34,34.17,44.12,32.54,41.75,39.63,9.97,False
4,mmdet_osnet,38.24,57.32,44.47,48.83,40.06,48.95,46.31,6.26,False
5,yolo_seg_osnet_seg,48.99,55.30,57.93,55.78,38.82,49.69,51.08,10.60,True

## Оверлеи (original + best)

Headless-рендер через `cv2.VideoWriter` (без `cv2.imshow`, работает в Colab):
- `overlays/original/` — baseline DeepSORT
- `overlays/best/` — лучшая связка (поменяйте `NAME`, если другая)

In [12]:
NAME = "yolo_osnet"

# Headless render (no cv2.imshow) — original baseline + best combo.
!python scripts/run_overlays.py --convert_h264
!python scripts/run_overlays.py \
    --results-dir results/tracking/{NAME} \
    --overlays-dir overlays/best \
    --convert_h264

import os
print("overlays/original:", sorted(os.listdir("overlays/original")))
print("overlays/best:", sorted(os.listdir("overlays/best")))

Rendering overlays from results/baseline/original -> overlays/original
Saving KITTI-17 -> overlays/original/KITTI-17.avi
Saving PETS09-S2L1 -> overlays/original/PETS09-S2L1.avi
Saving TUD-Campus -> overlays/original/TUD-Campus.avi
Saving TUD-Stadtmitte -> overlays/original/TUD-Stadtmitte.avi
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, avi, from 'overlays/original/KITTI-17.avi':
  Metadata:
    software        : Lavf62.3.100
  Duration: 00:00:14.50, start: 0.000000, bitrate: 7182 kb/s
  Stream #0:0: Video: mjpeg (Baseline) (MJPG / 0x47504A4D), yuvj420p(pc, bt470bg/unknown/unknown), 1224x370, 7227 kb/s, 10 fps, 10 tbr, 10 tbn, 10 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5a4fa6c43ec0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5a4fa6c43ec0] profile High, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x5a4fa6c43ec0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=5 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=8 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=10 scenecut=40 intra_refresh=0 rc_lookahead=50 rc=crf mbtree=1 crf=21.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'overlays/original/KITTI-17.mp4':
  Metadata:
    software        : Lavf62.3.100
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuvj420p(pc, bt470bg/unknown/unknown, progressive), 1224x370, q=2-31, 10 fps, 10240 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  145 fps= 12 q=-1.0 Lsize=    3569kB time=00:00:14.20 bitrate=2058.8kbits/s speed=1.19x
video:3566kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.072651%
[libx264 @ 0x5a4fa6c43ec0] frame I:1     Avg QP:18.59  size: 74374
[libx264 @ 0x5a4fa6c43ec0] frame P:36    Avg QP:19.65  size: 46488
[libx264 @ 0x5a4fa6c43ec0] frame B:108   Avg QP:23.32  size: 17621
[libx264 @ 0x5a4fa6c43ec0] consecutive B-frames:  0.7%  0.0%  0.0% 99.3%
[libx264 @ 0x5a4fa6c43ec0] mb I  I16..4:  7.8% 89.8%  2.4%
[libx264 @ 0x5a4fa6c43ec0] mb P  I16..4:  0.5% 14.7%  3.0%  P16..4: 29.3% 23.8% 25.1%  0.0%  0.0%    skip: 3.5%
[libx264 @ 0x5a4fa6c43ec0] mb B  I16..4:  0.2%  3.5%  1.5%  B16..8: 23.8% 16.1%  9.0%  direct:12.3%  skip:33.5%  L0:48.1% L1:31.1% BI:20.8%
[libx264 @ 0x5a4fa6c43ec0] 8x8 transform intra:75.4% inter:85.2%
[libx264 @ 0x5a4fa6c43ec0] direct mvs  spatial:98.1% temporal:1.9%
[libx264 @ 0x5a4fa6c43ec0] coded y,uvDC,uvAC intra: 83.1% 69.3% 42.6% inter: 42.7% 43.1% 14.8%
[libx264 @ 0x5a4fa6c43ec0] i16 v,h,dc,p: 43% 46%  9%  3%
[libx264 @ 0x5a4fa6c43ec0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 19% 28% 36%  2%  3%  3%  2%  3%  4%
[libx264 @ 0x5a4fa6c43ec0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 38% 16%  9%  4%  7%  9%  6%  6%  5%
[libx264 @ 0x5a4fa6c43ec0] i8c dc,h,v,p: 32% 32% 32%  4%
[libx264 @ 0x5a4fa6c43ec0] Weighted P-Frames: Y:33.3% UV:8.3%
[libx264 @ 0x5a4fa6c43ec0] ref P L0: 37.3% 12.2% 19.5% 14.1% 14.0%  2.8%
[libx264 @ 0x5a4fa6c43ec0] ref B L0: 59.5% 26.1% 10.5%  3.9%
[libx264 @ 0x5a4fa6c43ec0] ref B L1: 89.9% 10.1%
[libx264 @ 0x5a4fa6c43ec0] kb/s:2014.37
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, avi, from 'overlays/original/PETS09-S2L1.avi':
  Metadata:
    software        : Lavf62.3.100
  Duration: 00:01:53.57, start: 0.000000, bitrate: 4638 kb/s
  Stream #0:0: Video: mjpeg (Baseline) (MJPG / 0x47504A4D), yuvj420p(pc, bt470bg/unknown/unknown), 768x576, 4642 kb/s, 7 fps, 7 tbr, 7 tbn, 7 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x5a4d73572c80] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x5a4d73572c80] profile High, level 3.1, 4:2:0, 8-bit
[libx264 @ 0x5a4d73572c80] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=5 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=8 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=7 scenecut=40 intra_refresh=0 rc_lookahead=50 rc=crf mbtree=1 crf=21.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'overlays/original/PETS09-S2L1.mp4':
  Metadata:
    software        : Lavf62.3.100
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuvj420p(pc, bt470bg/unknown/unknown, progressive), 768x576, q=2-31, 7 fps, 14336 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  795 fps=9.7 q=-1.0 Lsize=   27548kB time=00:01:53.14 bitrate=1994.6kbits/s speed=1.37x
video:27538kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.037998%
[libx264 @ 0x5a4d73572c80] frame I:4     Avg QP:14.97  size: 94410
[libx264 @ 0x5a4d73572c80] frame P:200   Avg QP:17.36  size: 58797
[libx264 @ 0x5a4d73572c80] frame B:591   Avg QP:21.46  size: 27176
[libx264 @ 0x5a4d73572c80] consecutive B-frames:  0.9%  0.0%  0.0% 99.1%
[libx264 @ 0x5a4d73572c80] mb I  I16..4:  0.1% 95.1%  4.9%
[libx264 @ 0x5a4d73572c80] mb P  I16..4:  0.1% 12.2%  1.9%  P16..4: 21.0% 31.4% 33.3%  0.0%  0.0%    skip: 0.1%
[libx264 @ 0x5a4d73572c80] mb B  I16..4:  0.0%  3.1%  0.8%  B16..8: 22.8% 23.2% 14.3%  direct:19.4%  skip:16.5%  L0:48.2% L1:16.1% BI:35.7%
[libx264 @ 0x5a4d73572c80] 8x8 transform intra:84.2% inter:90.2%
[libx264 @ 0x5a4d73572c80] direct mvs  spatial:99.7% temporal:0.3%
[libx264 @ 0x5a4d73572c80] coded y,uvDC,uvAC intra: 97.8% 85.0% 47.3% inter: 73.0% 68.6% 19.0%
[libx264 @ 0x5a4d73572c80] i16 v,h,dc,p: 77% 14%  1%  8%
[libx264 @ 0x5a4d73572c80] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 10% 27% 49%  2%  1%  1%  4%  2%  4%
[libx264 @ 0x5a4d73572c80] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 36% 16%  8%  5%  6%  9%  7%  7%  6%
[libx264 @ 0x5a4d73572c80] i8c dc,h,v,p: 31% 35% 29%  4%
[libx264 @ 0x5a4d73572c80] Weighted P-Frames: Y:0.5% UV:0.0%
[libx264 @ 0x5a4d73572c80] ref P L0: 24.1%  6.8% 28.3% 17.9% 22.8%  0.1%
[libx264 @ 0x5a4d73572c80] ref B L0: 42.5% 35.2% 15.4%  6.9%
[libx264 @ 0x5a4d73572c80] ref B L1: 82.0% 18.0%
[libx264 @ 0x5a4d73572c80] kb/s:1986.26
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, avi, from 'overlays/original/TUD-Campus.avi':
  Metadata:
    software        : Lavf62.3.100
  Duration: 00:00:02.84, start: 0.000000, bitrate: 10411 kb/s
  Stream #0:0: Video: mjpeg (Baseline) (MJPG / 0x47504A4D), yuvj420p(pc, bt470bg/unknown/unknown), 640x480, 10538 kb/s, 25 fps, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x57b8c45e1ec0] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x57b8c45e1ec0] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x57b8c45e1ec0] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=5 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=8 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=50 rc=crf mbtree=1 crf=21.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'overlays/original/TUD-Campus.mp4':
  Metadata:
    software        : Lavf62.3.100
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuvj420p(pc, bt470bg/unknown/unknown, progressive), 640x480, q=2-31, 25 fps, 12800 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=   71 fps= 24 q=-1.0 Lsize=     531kB time=00:00:02.72 bitrate=1597.8kbits/s speed=0.918x
video:529kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.316686%
[libx264 @ 0x57b8c45e1ec0] frame I:1     Avg QP:23.72  size: 24890
[libx264 @ 0x57b8c45e1ec0] frame P:18    Avg QP:24.37  size: 14058
[libx264 @ 0x57b8c45e1ec0] frame B:52    Avg QP:27.30  size:  5056
[libx264 @ 0x57b8c45e1ec0] consecutive B-frames:  1.4%  2.8%  0.0% 95.8%
[libx264 @ 0x57b8c45e1ec0] mb I  I16..4:  2.0% 90.4%  7.6%
[libx264 @ 0x57b8c45e1ec0] mb P  I16..4:  0.4% 16.6%  5.5%  P16..4: 35.9% 12.4% 10.2%  0.0%  0.0%    skip:19.0%
[libx264 @ 0x57b8c45e1ec0] mb B  I16..4:  0.2%  1.9%  1.8%  B16..8: 25.1% 10.8%  3.9%  direct: 3.0%  skip:53.4%  L0:45.3% L1:40.6% BI:14.1%
[libx264 @ 0x57b8c45e1ec0] 8x8 transform intra:69.1% inter:71.9%
[libx264 @ 0x57b8c45e1ec0] direct mvs  spatial:96.2% temporal:3.8%
[libx264 @ 0x57b8c45e1ec0] coded y,uvDC,uvAC intra: 93.0% 79.2% 28.1% inter: 19.8% 20.9% 5.4%
[libx264 @ 0x57b8c45e1ec0] i16 v,h,dc,p: 48% 45%  2%  5%
[libx264 @ 0x57b8c45e1ec0] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 23% 28% 16%  4%  4%  6%  5%  7%  7%
[libx264 @ 0x57b8c45e1ec0] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 34% 24%  6%  4%  6%  8%  7%  5%  6%
[libx264 @ 0x57b8c45e1ec0] i8c dc,h,v,p: 19% 32% 42%  6%
[libx264 @ 0x57b8c45e1ec0] Weighted P-Frames: Y:5.6% UV:0.0%
[libx264 @ 0x57b8c45e1ec0] ref P L0: 44.0% 12.3% 24.2%  8.3% 11.3%
[libx264 @ 0x57b8c45e1ec0] ref B L0: 71.1% 19.2%  6.8%  2.9%
[libx264 @ 0x57b8c45e1ec0] ref B L1: 92.9%  7.1%
[libx264 @ 0x57b8c45e1ec0] kb/s:1523.54
ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Input #0, avi, from 'overlays/original/TUD-Stadtmitte.avi':
  Metadata:
    software        : Lavf62.3.100
  Duration: 00:00:07.16, start: 0.000000, bitrate: 10321 kb/s
  Stream #0:0: Video: mjpeg (Baseline) (MJPG / 0x47504A4D), yuvj420p(pc, bt470bg/unknown/unknown), 640x480, 10368 kb/s, 25 fps, 25 tbr, 25 tbn, 25 tbc
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
Press [q] to stop, [?] for help
[libx264 @ 0x59a4c10e1700] using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX FMA3 BMI2 AVX2 AVX512
[libx264 @ 0x59a4c10e1700] profile High, level 3.0, 4:2:0, 8-bit
[libx264 @ 0x59a4c10e1700] 264 - core 163 r3060 5db6aa6 - H.264/MPEG-4 AVC codec - Copyleft 2003-2021 - http://www.videolan.org/x264.html - options: cabac=1 ref=5 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=8 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=2 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=3 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=3 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=50 rc=crf mbtree=1 crf=21.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'overlays/original/TUD-Stadtmitte.mp4':
  Metadata:
    software        : Lavf62.3.100
    encoder         : Lavf58.76.100
  Stream #0:0: Video: h264 (avc1 / 0x31637661), yuvj420p(pc, bt470bg/unknown/unknown, progressive), 640x480, q=2-31, 25 fps, 12800 tbn
    Metadata:
      encoder         : Lavc58.134.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: N/A
frame=  179 fps= 25 q=-1.0 Lsize=    1200kB time=00:00:07.04 bitrate=1395.9kbits/s speed=0.996x
video:1197kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.247029%
[libx264 @ 0x59a4c10e1700] frame I:1     Avg QP:23.13  size: 28637
[libx264 @ 0x59a4c10e1700] frame P:45    Avg QP:22.64  size: 14843
[libx264 @ 0x59a4c10e1700] frame B:133   Avg QP:26.78  size:  3971
[libx264 @ 0x59a4c10e1700] consecutive B-frames:  0.6%  1.1%  0.0% 98.3%
[libx264 @ 0x59a4c10e1700] mb I  I16..4:  1.7% 96.4%  1.9%
[libx264 @ 0x59a4c10e1700] mb P  I16..4:  0.8% 12.3%  4.8%  P16..4: 36.3% 19.4% 17.0%  0.0%  0.0%    skip: 9.3%
[libx264 @ 0x59a4c10e1700] mb B  I16..4:  0.4%  1.4%  1.3%  B16..8: 28.0%  9.5%  3.1%  direct: 2.6%  skip:53.7%  L0:51.2% L1:37.6% BI:11.3%
[libx264 @ 0x59a4c10e1700] 8x8 transform intra:63.2% inter:63.3%
[libx264 @ 0x59a4c10e1700] direct mvs  spatial:98.5% temporal:1.5%
[libx264 @ 0x59a4c10e1700] coded y,uvDC,uvAC intra: 85.8% 84.4% 39.5% inter: 18.7% 26.2% 7.1%
[libx264 @ 0x59a4c10e1700] i16 v,h,dc,p: 64% 31%  1%  4%
[libx264 @ 0x59a4c10e1700] i8 v,h,dc,ddl,ddr,vr,hd,vl,hu: 30% 29% 20%  2%  2%  4%  2%  5%  4%
[libx264 @ 0x59a4c10e1700] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 46% 21%  5%  3%  4%  7%  4%  5%  4%
[libx264 @ 0x59a4c10e1700] i8c dc,h,v,p: 15% 29% 51%  5%

## Этап 6 — сегментация → маски убирают фон перед ReID

- `yolo_seg` — основной real-time вариант, **setup не нужен**
- `detectron2_seg` / `smp_seg` — optional quality mode (`setup_segmentation_colab.py`)

С флагом `--mask-background` фон зануляется до ReID.

In [13]:
# yolo_seg работает без detectron2; optional quality backends ниже
NAME = "yolo_seg_osnet_seg"
!python scripts/run_tracker.py --detector yolo_seg --reid osnet --mask-background --tracker-name {NAME}
!python scripts/run_eval.py --tracker-name {NAME} --results-dir results/tracking/{NAME}

# optional: detectron2 (сборка ~5–10 мин) + smp weights
# !python scripts/setup_segmentation_colab.py
# !python scripts/setup_segmentation_colab.py --download-smp-weights
# !python scripts/run_tracker.py --detector detectron2_seg --reid osnet --mask-background --tracker-name detectron2_seg_osnet_seg

Detector: yolo_seg | ReID: osnet | mask_background: True | identity: False | tracker_name: yolo_seg_osnet_seg
/usr/local/lib/python3.12/dist-packages/torchreid/models/osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)
Successfully loaded imagenet pretrained weights from "/root/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

Tracking TUD-Campus ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  TUD-Campus: 11.01 FPS (det 36.9ms | reid 42.5ms | track 11.4ms)

Tracking TUD-Stadtmitte ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  TUD-Stadtmitte: 13.74 FPS (det 32.1ms | reid 33.8ms | track 6.8ms)

Tracking KITTI-17 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  KITTI-17: 12.64 FPS (det 40.1ms | reid 33.7ms | track 5.3ms)

Tracking PETS09-S2L1 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  PETS09-S2L1: 11.85 FPS (det 43.1ms | reid 34.0ms | track 7.4ms)

Tracking MOT16-09 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  MOT16-09: 5.94 FPS (det 118.4ms | reid 37.1ms | track 12.9ms)

Tracking MOT16-11 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  MOT16-11: 6.44 FPS (det 110.1ms | reid 34.8ms | track 10.4ms)

=== Tracking FPS summary ===
Sequence                  FPS   det ms  reid ms  track ms
--------------------------------------------------------
KITTI-17                12.64     40.1     33.7       5.3
MOT16-09                 5.94    118.4     37.1      12.9
MOT16-11                 6.44    110.1     34.8      10.4
PETS09-S2L1             11.85     43.1     34.0       7.4
TUD-Campus              11.01     36.9     42.5      11.4
TUD-Stadtmitte          13.74     32.1     33.8       6.8
--------------------------------------------------------
MEAN                    10.27

Results: /content/DeepSORT_Project_CV/results/tracking/yolo_seg_osnet_seg
Evaluate: python scripts/run_eval.py --tracker-name yolo_seg_osnet_seg --results-dir /content/DeepSORT_Project_CV/results/tracking/yolo_seg_osnet_seg

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 4 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_seg_osnet_seg

1 eval_sequence(KITTI-17, yolo_seg_osnet_seg)                            0.0863 sec
2 eval_sequence(PETS09-S2L1, yolo_seg_osnet_seg)                         0.4738 sec
3 eval_sequence(TUD-Campus, yolo_seg_osnet_seg)                          0.0443 sec
4 eval_sequence(TUD-Stadtmitte, yolo_seg_osnet_seg)                      0.1022 sec

All sequences for yolo_seg_osnet_seg finished in 0.71 seconds

HOTA: yolo_seg_osnet_seg-pedestrianHOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
KITTI-17                           57.928    57.071    58.819    66.841    68.858    64.887    73.88     80.44     62.639    79.071    75.908    60.021
PETS09-S2L1                        55.779    61.498    50.67     72.791    68.347    61.596    65.906    79.978    60.714    75.908    75.358    57.203
TUD-Campus                         48.988    47.164    51.113    63.554    56.058    60.973    65.039    78.299    56.968    68.824    71.726    49.365
TUD-Stadtmitte                     55.298    60.928    50.358    65.676    74.947    63.505    61.738    80.171    57.491    73.576    75.644    55.655
COMBINED                           55.539    60.052    51.453    70.453    68.642    62.232    66.001    79.935    60.193    75.455    75.272    56.797

CLEAR: yolo_seg_osnet_seg-pedestrianMOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
KITTI-17                           65.154    77.739    66.325    81.698    84.163    66.667    33.333    0         46.967    558       125       105       8         6         3         0         15
PETS09-S2L1                        75.804    76.638    76.653    91.577    85.987    84.211    15.789    0         54.41     4099      377       668       38        16        3         0         87
TUD-Campus                         47.632    75.124    50.975    82.173    72.482    62.5      37.5      0         27.191    295       64        112       12        5         3         0         11
TUD-Stadtmitte                     76.817    77.211    77.422    82.526    94.176    80        20        0         58.01     954       202       59        7         8         2         0         13
COMBINED                           73.374    76.759    74.348    88.493    86.219    76.087    23.913    0         52.807    5906      768       944       65        35        11        0         126

Identity: yolo_seg_osnet_seg-pedestrianIDF1      IDR       IDP       IDTP      IDFN      IDFP
KITTI-17                           80.535    79.356    81.75     542       141       121
PETS09-S2L1                        72.963    75.335    70.736    3372      1104      1395
TUD-Campus                         69.191    73.816    65.111    265       94        142
TUD-Stadtmitte                     72.384    67.907    77.493    785       371       228
COMBINED                           73.41     74.378    72.467    4964      1710      1886

Count: yolo_seg_osnet_seg-pedestrianDets      GT_Dets   IDs       GT_IDs
KITTI-17                           663       683       14        9
PETS09-S2L1                        4767      4476      35        19
TUD-Campus                         407       359       13        8
TUD-Stadtmitte                     1013      1156      12        10
COMBINED                           6850      6674      74        46

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 2 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_seg_osnet_seg

5 eval_sequence(MOT16-09, yolo_seg_osnet_seg)                            0.4052 sec
6 eval_sequence(MOT16-11, yolo_seg_osnet_seg)                            0.6563 sec

All sequences for yolo_seg_osnet_seg finished in 1.06 seconds

HOTA: yolo_seg_osnet_seg-pedestrianHOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
MOT16-09                           38.815    47.928    31.614    55.567    69.222    41.56     54.563    81.811    41.883    52.967    74.815    39.628
MOT16-11                           49.692    49.802    50.02     54.839    76.819    57.801    74.091    84.347    52.295    62.118    79.203    49.199
COMBINED                           45.915    49.073    43.403    55.104    73.842    52.011    67.152    83.405    48.811    58.875    77.53     45.646

CLEAR: yolo_seg_osnet_seg-pedestrianMOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
MOT16-09                           52.863    79.891    54.48     67.377    83.934    32        56        12        39.314    3542      1715      678       85        8         14        3         92
MOT16-11                           52.91     83.135    53.27     62.328    87.311    21.739    36.232    42.029    42.399    5718      3456      831       33        15        25        29        57
COMBINED                           52.893    81.894    53.711    64.167    85.988    24.468    41.489    34.043    41.275    9260      5171      1509      118       23        39        32        149

Identity: yolo_seg_osnet_seg-pedestrianIDF1      IDR       IDP       IDTP      IDFN      IDFP
MOT16-09                           46.492    41.906    52.204    2203      3054      2017
MOT16-11                           59.047    50.6      70.881    4642      4532      1907
COMBINED                           54.325    47.433    63.562    6845      7586      3924

Count: yolo_seg_osnet_seg-pedestrianDets      GT_Dets   IDs       GT_IDs
MOT16-09                           4220      5257      50        25
MOT16-11                           6549      9174      86        69
COMBINED                           10769     14431     136       94

=== HOTA summary (TrackEval) ===

Tracker: yolo_seg_osnet_seg
Sequence                 HOTA     MOTA     IDF1
------------------------------------------------
KITTI-17                57.93    65.15    80.53
MOT16-09                38.82    52.86    46.49
MOT16-11                49.69    52.91    59.05
PETS09-S2L1             55.78    75.80    72.96
TUD-Campus              48.99    47.63    69.19
TUD-Stadtmitte          55.30    76.82    72.38
------------------------------------------------
MEAN (6 videos)         51.08

Saved: {'csv': 'results/eval/summary.csv', 'json': 'results/eval/summary.json'}

## Этап 7 — Additional: автономная база идентичностей (body ReID)

Онлайн-галерея (`IdentityDatabase`) + kNN lookup + majority-vote по окну + conflict resolution.
Встроена в live-трекер: `--identity` (sidecar `*_identity.csv`: track_id → identity).
Оценка на GT-кропах: Fowlkes–Mallows / ARI / V-measure для `db_raw` и `resolved`.
Параметры: `configs/identity.yaml` или CLI `--radius --k --representation --window`.

In [14]:
# Standalone eval на GT-кропах (defaults from configs/identity.yaml).
!python scripts/download_reid_models.py
!python scripts/run_identity_eval.py --reid osnet

# Live-трекер с identity DB (лучшая real-time связка + --identity)
NAME = "yolo_osnet_id"
!python scripts/run_tracker.py --detector yolo --reid osnet --identity --tracker-name {NAME}
# Sidecar: results/tracking/{NAME}/<seq>_identity.csv

# kNN-режим галереи (ablation)
!python scripts/run_identity_eval.py --reid osnet --representation knn --k 5 --radius 0.35

OK (exists): /content/DeepSORT_Project_CV/resources/models/fastreid/market_bot_R50.pth
OK (exists): /content/DeepSORT_Project_CV/resources/models/fastreid/market_bot_R50-ibn.pth
OK (exists): /content/DeepSORT_Project_CV/resources/models/torchreid/market1501_resnet50.pth
Done. osnet (torchreid) downloads weights on first run; resnet50 uses resources/models/torchreid/market1501_resnet50.pth; resnet50_ibn/fastreid use fast-reid checkpoints.
ReID: osnet | params: IdentityParams(radius=0.4, k=1, representation='centroid', window=30, conflict_policy='distance', max_per_identity=50)
/usr/local/lib/python3.12/dist-packages/torchreid/models/osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)
Successfully loaded imagenet pretrained weights from "/root/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
  TUD-Campus ...
  TUD-Stadtmitte ...
  KITTI-17 ...
  PETS09-S2L1 ...
  MOT16-09 ...
  MOT16-11 ...

=== Identity DB summary (GT crops) ===
Model: osnet | params: {'radius': 0.4, 'k': 1, 'representation': 'centroid', 'window': 30, 'conflict_policy': 'distance', 'max_per_identity': 50}
Sequence           labels        FM     ARI       V  trueID  predID      N
----------------------------------------------------------------------
KITTI-17           db_raw     0.486   0.414   0.580       9      28    683
KITTI-17           resolved   0.668   0.609   0.718       9      93    683
MOT16-09           db_raw     0.522   0.465   0.707      25     233   4273
MOT16-09           resolved   0.588   0.538   0.765      25     347   4273
MOT16-11           db_raw     0.523   0.458   0.789      69     304   8114
MOT16-11           resolved   0.567   0.505   0.836      69     426   8114
PETS09-S2L1        db_raw     0.408   0.366   0.587      19      46   4476
PETS09-S2L1        resolved   0.470   0.432   0.688      19      98   4476
TUD-Campus         db_raw     0.712   0.663   0.744       8       9    359
TUD-Campus         resolved   0.933   0.919   0.959       8       9    359
TUD-Stadtmitte     db_raw     0.633   0.564   0.694      10      46   1156
TUD-Stadtmitte     resolved   0.716   0.661   0.794      10      63   1156
----------------------------------------------------------------------
MEAN resolved FM (6 videos): 0.657

Saved: {'csv': '/content/DeepSORT_Project_CV/results/identity/summary.csv', 'json': '/content/DeepSORT_Project_CV/results/identity/summary.json'}
Detector: yolo | ReID: osnet | mask_background: False | identity: True | tracker_name: yolo_osnet_id
/usr/local/lib/python3.12/dist-packages/torchreid/models/osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)
Successfully loaded imagenet pretrained weights from "/root/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

Tracking TUD-Campus ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  TUD-Campus: 16.92 FPS (det 13.6ms | reid 38.3ms | track 7.2ms | identity 0.0ms | gallery 0)

Tracking TUD-Stadtmitte ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  TUD-Stadtmitte: 17.88 FPS (det 14.2ms | reid 35.0ms | track 6.7ms | identity 0.0ms | gallery 0)

Tracking KITTI-17 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  KITTI-17: 23.81 FPS (det 11.2ms | reid 27.4ms | track 3.3ms | identity 0.0ms | gallery 0)

Tracking PETS09-S2L1 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  PETS09-S2L1: 17.74 FPS (det 15.0ms | reid 34.7ms | track 6.6ms | identity 0.0ms | gallery 0)

Tracking MOT16-09 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  MOT16-09: 14.02 FPS (det 16.0ms | reid 43.0ms | track 12.2ms | identity 0.0ms | gallery 0)

Tracking MOT16-11 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  MOT16-11: 15.86 FPS (det 15.5ms | reid 38.5ms | track 9.0ms | identity 0.0ms | gallery 0)

=== Tracking FPS summary ===
Sequence                  FPS   det ms  reid ms  track ms    id ms
----------------------------------------------------------------
KITTI-17                23.81     11.2     27.4       3.3      0.0
MOT16-09                14.02     16.0     43.0      12.2      0.0
MOT16-11                15.86     15.5     38.5       9.0      0.0
PETS09-S2L1             17.74     15.0     34.7       6.6      0.0
TUD-Campus              16.92     13.6     38.3       7.2      0.0
TUD-Stadtmitte          17.88     14.2     35.0       6.7      0.0
--------------------------------------------------------
MEAN                    17.71

Results: /content/DeepSORT_Project_CV/results/tracking/yolo_osnet_id
Evaluate: python scripts/run_eval.py --tracker-name yolo_osnet_id --results-dir /content/DeepSORT_Project_CV/results/tracking/yolo_osnet_id
ReID: osnet | params: IdentityParams(radius=0.35, k=5, representation='knn', window=30, conflict_policy='distance', max_per_identity=50)
/usr/local/lib/python3.12/dist-packages/torchreid/models/osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)
Successfully loaded imagenet pretrained weights from "/root/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
  TUD-Campus ...
  TUD-Stadtmitte ...
  KITTI-17 ...
  PETS09-S2L1 ...
  MOT16-09 ...
  MOT16-11 ...

=== Identity DB summary (GT crops) ===
Model: osnet | params: {'radius': 0.35, 'k': 5, 'representation': 'knn', 'window': 30, 'conflict_policy': 'distance', 'max_per_identity': 50}
Sequence           labels        FM     ARI       V  trueID  predID      N
----------------------------------------------------------------------
KITTI-17           db_raw     0.382   0.086   0.255       9       4    683
KITTI-17           resolved   0.246   0.159   0.483       9     430    683
MOT16-09           db_raw     0.294   0.129   0.511      25      16   4273
MOT16-09           resolved   0.259   0.220   0.565      25    2365   4273
MOT16-11           db_raw     0.319   0.144   0.623      69      41   8114
MOT16-11           resolved   0.322   0.285   0.645      69    4262   8114
PETS09-S2L1        db_raw     0.330   0.223   0.542      19      62   4476
PETS09-S2L1        resolved   0.366   0.323   0.580      19    1373   4476
TUD-Campus         db_raw     0.390   0.000   0.000       8       1    359
TUD-Campus         resolved   0.079   0.002   0.452       8     281    359
TUD-Stadtmitte     db_raw     0.366   0.023   0.144      10       2   1156
TUD-Stadtmitte     resolved   0.277   0.174   0.494      10     903   1156
----------------------------------------------------------------------
MEAN resolved FM (6 videos): 0.258

Saved: {'csv': '/content/DeepSORT_Project_CV/results/identity/summary.csv', 'json': '/content/DeepSORT_Project_CV/results/identity/summary.json'}

# Эволюция параметров, per-video, GT-bbox ReID

- sweep по параметрам трекера (`max_cosine_distance`, `min_confidence`) → HOTA + FPS;
- sweep по параметрам identity DB (`radius`, `representation`) → FM/ARI;
- финальный прогон лучшей связки с **per-video** параметрами (`configs/tracker_params.yaml`);
- оценка ReID на **GT-боксах** (детектор выключен) → HOTA, изолируем качество ReID/ассоциации.

In [15]:
!git pull

# Эволюция параметров трекера (HOTA по каждому видео + FPS) на лучшей связке yolo+osnet
!python scripts/run_param_sweep.py --param max_cosine_distance --values 0.1 0.2 0.3 0.4 --detector yolo --reid osnet
!python scripts/run_param_sweep.py --param min_confidence --values 0.2 0.3 0.4 0.5 --detector yolo --reid osnet

import pandas as pd
display(pd.read_csv("results/param_sweep/sweep_max_cosine_distance.csv"))
display(pd.read_csv("results/param_sweep/sweep_min_confidence.csv"))

remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 8 (delta 6), reused 8 (delta 6), pack-reused 0 (from 0)
Unpacking objects: 100% (8/8), 2.69 KiB | 919.00 KiB/s, done.
From https://github.com/Valeriia-Reznik-Dev/DeepSORT_Project_CV
   3b948d2..262a487  master     -> origin/master
Updating 3b948d2..262a487
Fast-forward
 notebooks/baseline_colab.ipynb  |  1 +
 reid/torchreid_ext.py           | 94 ++++++++++++++++++++++++++++++++++++++++-
 scripts/download_reid_models.py | 69 +++++++++++++++++++++++++-----
 3 files changed, 152 insertions(+), 12 deletions(-)
Loading yolo + osnet ...
/usr/local/lib/python3.12/dist-packages/torchreid/models/osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)
Successfully loaded imagenet pretrained weights from "/root/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

=== max_cosine_distance = 0.1 ===
  TUD-Campus: 21.93 FPS
  TUD-Stadtmitte: 18.11 FPS
  KITTI-17: 16.79 FPS
  PETS09-S2L1: 17.05 FPS
  MOT16-09: 14.33 FPS
  MOT16-11: 15.09 FPS

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 4 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_osnet__max_cosine_distance_0.1

1 eval_sequence(KITTI-17, yolo_osnet__max_cosine_distance_0.1)           0.1159 sec
2 eval_sequence(PETS09-S2L1, yolo_osnet__max_cosine_distance_0.1)        0.4896 sec
3 eval_sequence(TUD-Campus, yolo_osnet__max_cosine_distance_0.1)         0.0448 sec
4 eval_sequence(TUD-Stadtmitte, yolo_osnet__max_cosine_distance_0.1)     0.1181 sec

All sequences for yolo_osnet__max_cosine_distance_0.1 finished in 0.77 seconds

HOTA: yolo_osnet__max_cosine_distance_0.1-pedestrianHOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
KITTI-17                           54.775    57.225    52.48     64.09     71.878    56.123    77.232    80.08     57.978    74.361    75.304    55.997
PETS09-S2L1                        45.504    61.936    33.648    71.278    70.011    37.881    72.322    79.761    48.949    61.035    74.995    45.773
TUD-Campus                         44.166    47.057    41.586    62.557    56.712    47.149    69.561    78.748    50.999    60.554    72.917    44.154
TUD-Stadtmitte                     59.131    60.262    58.117    65.689    74.962    61.714    80.436    81.017    61.772    77.746    77.178    60.002
COMBINED                           48.896    60.241    39.868    69.106    70.146    44.022    74.056    79.937    52.476    65.479    75.27     49.286

CLEAR: yolo_osnet__max_cosine_distance_0.1-pedestrianMOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
KITTI-17                           66.618    77.49     68.082    78.624    88.177    55.556    44.444    0         48.92     537       146       72        10        5         4         0         9
PETS09-S2L1                        76.162    76.35     77.681    89.745    88.15     84.211    15.789    0         54.937    4017      459       540       68        16        3         0         87
TUD-Campus                         47.911    74.913    50.139    80.223    72.727    50        50        0         27.785    288       71        108       8         4         4         0         8
TUD-Stadtmitte                     74.048    78.325    74.654    81.142    92.596    80        20        0         56.461    938       218       75        7         8         2         0         9
COMBINED                           73.299    76.705    74.693    86.605    87.909    71.739    28.261    0         53.125    5780      894       795       93        33        13        0         113

Identity: yolo_osnet__max_cosine_distance_0.1-pedestrianIDF1      IDR       IDP       IDTP      IDFN      IDFP
KITTI-17                           74.768    70.717    79.31     483       200       126
PETS09-S2L1                        52.474    52.949    52.008    2370      2106      2187
TUD-Campus                         59.868    62.953    57.071    226       133       170
TUD-Stadtmitte                     77.547    72.751    83.021    841       315       172
COMBINED                           59.174    58.735    59.62     3920      2754      2655

Count: yolo_osnet__max_cosine_distance_0.1-pedestrianDets      GT_Dets   IDs       GT_IDs
KITTI-17                           609       683       20        9
PETS09-S2L1                        4557      4476      79        19
TUD-Campus                         396       359       19        8
TUD-Stadtmitte                     1013      1156      21        10
COMBINED                           6575      6674      139       46

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 2 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_osnet__max_cosine_distance_0.1

5 eval_sequence(MOT16-09, yolo_osnet__max_cosine_distance_0.1)           0.4594 sec
6 eval_sequence(MOT16-11, yolo_osnet__max_cosine_distance_0.1)           0.7067 sec

All sequences for yolo_osnet__max_cosine_distance_0.1 finished in 1.17 seconds

HOTA: yolo_osnet__max_cosine_distance_0.1-pedestrianHOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
MOT16-09                           42.514    49.996    36.519    54.914    75.002    38.658    81.634    82.363    44.708    54.457    77.314    42.103
MOT16-11                           47.585    49.609    45.977    54.302    77.608    48.737    85.205    84.488    49.917    58.973    79.407    46.829
COMBINED                           45.811    49.731    42.604    54.525    76.632    45.149    84.135    83.706    48.123    57.364    78.625    45.102

CLEAR: yolo_osnet__max_cosine_distance_0.1-pedestrianMOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
MOT16-09                           56.496    80.041    57.999    65.608    89.608    32        60        8         43.401    3449      1808      400       79        8         15        2         74
MOT16-11                           52.845    83.252    53.379    61.674    88.145    23.188    34.783    42.029    42.516    5658      3516      761       49        16        24        29        47
COMBINED                           54.175    82.036    55.062    63.107    88.693    25.532    41.489    32.979    42.839    9107      5324      1161      128       24        39        31        121

Identity: yolo_osnet__max_cosine_distance_0.1-pedestrianIDF1      IDR       IDP       IDTP      IDFN      IDFP
MOT16-09                           50.231    43.504    59.418    2287      2970      1562
MOT16-11                           53.858    45.771    65.415    4199      4975      2220
COMBINED                           52.52     44.945    63.167    6486      7945      3782

Count: yolo_osnet__max_cosine_distance_0.1-pedestrianDets      GT_Dets   IDs       GT_IDs
MOT16-09                           3849      5257      116       25
MOT16-11                           6419      9174      137       69
COMBINED                           10268     14431     253       94

=== max_cosine_distance = 0.2 ===
  TUD-Campus: 21.18 FPS
  TUD-Stadtmitte: 17.05 FPS
  KITTI-17: 17.15 FPS
  PETS09-S2L1: 17.13 FPS
  MOT16-09: 14.41 FPS
  MOT16-11: 14.98 FPS

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 4 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_osnet__max_cosine_distance_0.2

7 eval_sequence(KITTI-17, yolo_osnet__max_cosine_distance_0.2)           0.1228 sec
8 eval_sequence(PETS09-S2L1, yolo_osnet__max_cosine_distance_0.2)        0.5098 sec
9 eval_sequence(TUD-Campus, yolo_osnet__max_cosine_distance_0.2)         0.0454 sec
10 eval_sequence(TUD-Stadtmitte, yolo_osnet__max_cosine_distance_0.2)     0.1263 sec

All sequences for yolo_osnet__max_cosine_distance_0.2 finished in 0.81 seconds

HOTA: yolo_osnet__max_cosine_distance_0.2-pedestrianHOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
KITTI-17                           55.708    56.522    54.955    65.724    68.638    59.582    74.801    79.826    60.073    76.311    74.929    57.179
PETS09-S2L1                        52.427    63.524    43.374    73.212    70.396    55.692    61.184    80.032    56.334    71.257    75.452    53.765
TUD-Campus                         47.956    47.445    48.649    66.046    55.269    60.149    63.451    79.583    56.67     65.199    73.903    48.184
TUD-Stadtmitte                     55.113    60.653    50.175    66.878    73.981    63.936    61.676    80.957    57.917    72.981    76.716    55.988
COMBINED                           52.957    61.277    45.87     70.963    69.822    57.658    62.703    80.143    57.04     71.707    75.525    54.157

CLEAR: yolo_osnet__max_cosine_distance_0.2-pedestrianMOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
KITTI-17                           65.154    77.057    66.471    81.113    84.709    55.556    44.444    0         46.544    554       129       100       9         5         4         0         11
PETS09-S2L1                        79.893    76.656    80.451    92.225    88.679    84.211    15.789    0         58.363    4128      348       527       25        16        3         0         86
TUD-Campus                         47.354    75.926    48.189    83.844    70.163    50        50        0         27.169    301       58        128       3         4         4         0         7
TUD-Stadtmitte                     74.913    77.788    75.346    82.872    91.675    70        30        0         56.506    958       198       87        5         7         3         0         10
COMBINED                           75.772    76.839    76.401    89.017    87.587    69.565    30.435    0         55.154    5941      733       842       42        32        14        0         114

Identity: yolo_osnet__max_cosine_distance_0.2-pedestrianIDF1      IDR       IDP       IDTP      IDFN      IDFP
KITTI-17                           75.093    73.499    76.758    502       181       152
PETS09-S2L1                        66.433    67.761    65.156    3033      1443      1622
TUD-Campus                         68.528    75.209    62.937    270       89        159
TUD-Stadtmitte                     69.332    66.003    73.014    763       393       282
COMBINED                           67.89     68.445    67.345    4568      2106      2215

Count: yolo_osnet__max_cosine_distance_0.2-pedestrianDets      GT_Dets   IDs       GT_IDs
KITTI-17                           654       683       13        9
PETS09-S2L1                        4655      4476      30        19
TUD-Campus                         429       359       12        8
TUD-Stadtmitte                     1045      1156      12        10
COMBINED                           6783      6674      67        46

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 2 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_osnet__max_cosine_distance_0.2

11 eval_sequence(MOT16-09, yolo_osnet__max_cosine_distance_0.2)           0.4554 sec
12 eval_sequence(MOT16-11, yolo_osnet__max_cosine_distance_0.2)           0.7397 sec

All sequences for yolo_osnet__max_cosine_distance_0.2 finished in 1.20 seconds

HOTA: yolo_osnet__max_cosine_distance_0.2-pedestrianHOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
MOT16-09                           44.232    50.56     39.019    56.472    73.429    43.93     68.924    82.155    46.889    57.365    76.229    43.729
MOT16-11                           51.95     50.007    54.321    55.154    76.861    59.683    82.11     84.473    54.69     65.045    79.386    51.636
COMBINED                           49.267    50.191    48.79     55.634    75.555    54.058    77.418    83.612    52.026    62.348    78.187    48.748

CLEAR: yolo_osnet__max_cosine_distance_0.2-pedestrianMOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
MOT16-09                           57.409    80.159    58.798    67.852    88.227    40        48        12        43.946    3567      1690      476       73        10        12        3         87
MOT16-11                           53.041    83.303    53.314    62.535    87.149    24.638    33.333    42.029    42.6      5737      3437      846       25        17        23        29        50
COMBINED                           54.632    82.098    55.311    64.472    87.559    28.723    37.234    34.043    43.09     9304      5127      1322      98        27        35        32        137

Identity: yolo_osnet__max_cosine_distance_0.2-pedestrianIDF1      IDR       IDP       IDTP      IDFN      IDFP
MOT16-09                           55.161    48.792    63.443    2565      2692      1478
MOT16-11                           60.595    52.038    72.52     4774      4400      1809
COMBINED                           58.578    50.856    69.066    7339      7092      3287

Count: yolo_osnet__max_cosine_distance_0.2-pedestrianDets      GT_Dets   IDs       GT_IDs
MOT16-09                           4043      5257      53        25
MOT16-11                           6583      9174      87        69
COMBINED                           10626     14431     140       94

=== max_cosine_distance = 0.3 ===
  TUD-Campus: 20.50 FPS
  TUD-Stadtmitte: 16.24 FPS
  KITTI-17: 15.48 FPS
  PETS09-S2L1: 16.39 FPS
  MOT16-09: 13.53 FPS
  MOT16-11: 15.35 FPS

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 4 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_osnet__max_cosine_distance_0.3

13 eval_sequence(KITTI-17, yolo_osnet__max_cosine_distance_0.3)           0.1252 sec
14 eval_sequence(PETS09-S2L1, yolo_osnet__max_cosine_distance_0.3)        0.5100 sec
15 eval_sequence(TUD-Campus, yolo_osnet__max_cosine_distance_0.3)         0.0481 sec
16 eval_sequence(TUD-Stadtmitte, yolo_osnet__max_cosine_distance_0.3)     0.1142 sec

All sequences for yolo_osnet__max_cosine_distance_0.3 finished in 0.80 seconds

HOTA: yolo_osnet__max_cosine_distance_0.3-pedestrianHOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
KITTI-17                           56.576    56.873    56.314    66.425    68.532    62.016    73.123    80.053    61.129    77.94     75.185    58.599
PETS09-S2L1                        52.533    63.392    43.633    73.366    70.108    59.154    58.805    80.025    56.561    71.449    75.44     53.901
TUD-Campus                         43.504    47.547    39.988    66.251    55.312    55.376    50.171    79.704    51.448    59.219    73.958    43.798
TUD-Stadtmitte                     51.292    60.261    43.781    66.973    73.315    58.56     57.083    80.9      54.14     67.887    76.278    51.783
COMBINED                           52.239    61.17     44.71     71.165    69.52     59.165    59.496    80.151    56.395    70.846    75.475    53.471

CLEAR: yolo_osnet__max_cosine_distance_0.3-pedestrianMOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
KITTI-17                           65.3      77.39     66.179    81.552    84.139    55.556    44.444    0         46.861    557       126       105       6         5         4         0         11
PETS09-S2L1                        79.625    76.65     80.161    92.404    88.301    84.211    15.789    0         58.048    4136      340       548       24        16        3         0         84
TUD-Campus                         46.797    76.135    47.911    83.844    70        50        50        0         26.788    301       58        129       4         4         4         0         8
TUD-Stadtmitte                     73.443    77.808    74.048    82.699    90.53     60        40        0         55.091    956       200       100       7         6         4         0         10
COMBINED                           75.322    76.879    75.936    89.152    87.09     67.391    32.609    0         54.71     5950      724       882       41        31        15        0         113

Identity: yolo_osnet__max_cosine_distance_0.3-pedestrianIDF1      IDR       IDP       IDTP      IDFN      IDFP
KITTI-17                           77.472    76.281    78.701    521       162       141
PETS09-S2L1                        66.376    67.918    64.902    3040      1436      1644
TUD-Campus                         56.781    62.396    52.093    224       135       206
TUD-Stadtmitte                     63.562    60.813    66.572    703       453       353
COMBINED                           66.459    67.246    65.691    4488      2186      2344

Count: yolo_osnet__max_cosine_distance_0.3-pedestrianDets      GT_Dets   IDs       GT_IDs
KITTI-17                           662       683       12        9
PETS09-S2L1                        4684      4476      27        19
TUD-Campus                         430       359       11        8
TUD-Stadtmitte                     1056      1156      11        10

,max_cosine_distance,TUD-Campus,TUD-Stadtmitte,KITTI-17,PETS09-S2L1,MOT16-09,MOT16-11,MEAN,mean_fps
0,0.1,44.17,59.13,54.77,45.50,42.51,47.58,48.95,17.22
1,0.2,47.96,55.11,55.71,52.43,44.23,51.95,51.23,16.99
2,0.3,43.50,51.29,56.58,52.53,39.84,47.62,48.56,16.25
3,0.4,43.50,51.29,56.50,52.54,39.12,44.21,47.86,16.52

,min_confidence,TUD-Campus,TUD-Stadtmitte,KITTI-17,PETS09-S2L1,MOT16-09,MOT16-11,MEAN,mean_fps
0,0.2,47.96,55.11,55.71,52.43,44.23,51.95,51.23,16.59
1,0.3,47.96,55.11,55.71,52.43,44.23,51.95,51.23,16.68
2,0.4,52.96,54.76,57.68,51.68,45.48,53.01,52.60,17.54
3,0.5,46.26,52.47,55.76,53.34,44.86,51.35,50.67,18.67

In [16]:
# Эволюция параметров identity DB (FM/ARI на GT-кропах)
!python scripts/run_identity_sweep.py --param radius --values 0.2 0.25 0.3 0.35 0.4 --reid osnet
!python scripts/run_identity_sweep.py --param representation --values centroid knn --reid osnet

import pandas as pd
display(pd.read_csv("results/identity_sweep/sweep_radius.csv"))
display(pd.read_csv("results/identity_sweep/sweep_representation.csv"))

Loading ReID: osnet ...
/usr/local/lib/python3.12/dist-packages/torchreid/models/osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)
Successfully loaded imagenet pretrained weights from "/root/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

=== radius = 0.2 ===
  TUD-Campus ...
  TUD-Stadtmitte ...
  KITTI-17 ...
  PETS09-S2L1 ...
  MOT16-09 ...
  MOT16-11 ...

=== radius = 0.25 ===
  TUD-Campus ...
  TUD-Stadtmitte ...
  KITTI-17 ...
  PETS09-S2L1 ...
  MOT16-09 ...
  MOT16-11 ...

=== radius = 0.3 ===
  TUD-Campus ...
  TUD-Stadtmitte ...
  KITTI-17 ...
  PETS09-S2L1 ...
  MOT16-09 ...
  MOT16-11 ...

=== radius = 0.35 ===
  TUD-Campus ...
  TUD-Stadtmitte ...
  KITTI-17 ...
  PETS09-S2L1 ...
  MOT16-09 ...
  MOT16-11 ...

=== radius = 0.4 ===
  TUD-Campus ...
  TUD-Stadtmitte ...
  KITTI-17 ...
  PETS09-S2L1 ...
  MOT16-09 ...
  MOT16-11 ...

============================================================================================
IDENTITY-DB PARAMETER EVOLUTION: radius  (reid=osnet)
============================================================================================
radius             res_FM  res_ARI    res_V   raw_FM   predID   trueID
------------------------------------------------------------------------
0.2                 0.638    0.581    0.782    0.548    167.8     23.3
0.25                0.641    0.590    0.782    0.544    187.2     23.3
0.3                 0.655    0.608    0.794    0.553    185.7     23.3
0.35                0.650    0.602    0.789    0.547    173.8     23.3
0.4                 0.657    0.611    0.793    0.547    172.7     23.3
------------------------------------------------------------------------
BEST radius by resolved FM: 0.4 (FM 0.657)

Saved: /content/DeepSORT_Project_CV/results/identity_sweep/sweep_radius.csv
Loading ReID: osnet ...
/usr/local/lib/python3.12/dist-packages/torchreid/models/osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)
Successfully loaded imagenet pretrained weights from "/root/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

=== representation = centroid ===
  TUD-Campus ...
  TUD-Stadtmitte ...
  KITTI-17 ...
  PETS09-S2L1 ...
  MOT16-09 ...
  MOT16-11 ...

=== representation = knn ===
  TUD-Campus ...
  TUD-Stadtmitte ...
  KITTI-17 ...
  PETS09-S2L1 ...
  MOT16-09 ...
  MOT16-11 ...

============================================================================================
IDENTITY-DB PARAMETER EVOLUTION: representation  (reid=osnet)
============================================================================================
representation     res_FM  res_ARI    res_V   raw_FM   predID   trueID
------------------------------------------------------------------------
centroid            0.657    0.611    0.793    0.547    172.7     23.3
knn                 0.616    0.571    0.749    0.583    255.8     23.3
------------------------------------------------------------------------
BEST representation by resolved FM: centroid (FM 0.657)

Saved: /content/DeepSORT_Project_CV/results/identity_sweep/sweep_representation.csv

,radius,resolved_fm,resolved_ari,resolved_v,db_raw_fm,pred_ids,true_ids
0,0.20,0.638,0.581,0.782,0.548,167.8,23.3
1,0.25,0.641,0.590,0.782,0.544,187.2,23.3
2,0.30,0.655,0.608,0.794,0.553,185.7,23.3
3,0.35,0.650,0.602,0.789,0.547,173.8,23.3
4,0.40,0.657,0.611,0.793,0.547,172.7,23.3

,representation,resolved_fm,resolved_ari,resolved_v,db_raw_fm,pred_ids,true_ids
0,centroid,0.657,0.611,0.793,0.547,172.7,23.3
1,knn,0.616,0.571,0.749,0.583,255.8,23.3

In [17]:
# Финальный прогон лучшей связки с per-video параметрами (configs/tracker_params.yaml)
NAME = "yolo_osnet_pv"
!python scripts/run_tracker.py --detector yolo --reid osnet \
    --params-config configs/tracker_params.yaml --tracker-name {NAME}
!python scripts/run_eval.py --tracker-name {NAME} --results-dir results/tracking/{NAME}

Detector: yolo | ReID: osnet | mask_background: False | identity: False | tracker_name: yolo_osnet_pv
/usr/local/lib/python3.12/dist-packages/torchreid/models/osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)
Successfully loaded imagenet pretrained weights from "/root/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

Tracking TUD-Campus ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  TUD-Campus: 12.87 FPS (det 18.2ms | reid 48.0ms | track 11.5ms)

Tracking TUD-Stadtmitte ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  TUD-Stadtmitte: 17.97 FPS (det 13.6ms | reid 35.8ms | track 6.1ms)

Tracking KITTI-17 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  KITTI-17: 20.43 FPS (det 13.3ms | reid 31.5ms | track 4.1ms)

Tracking PETS09-S2L1 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=0.9, max_cosine_distance=0.2, nn_budget=100)
  PETS09-S2L1: 16.85 FPS (det 16.3ms | reid 36.0ms | track 7.1ms)

Tracking MOT16-09 ... params=TrackerParams(min_confidence=0.4, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.25, nn_budget=100)
  MOT16-09: 14.30 FPS (det 17.0ms | reid 41.7ms | track 11.2ms)

Tracking MOT16-11 ... params=TrackerParams(min_confidence=0.4, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.3, nn_budget=150)
  MOT16-11: 14.90 FPS (det 17.4ms | reid 39.4ms | track 10.3ms)

=== Tracking FPS summary ===
Sequence                  FPS   det ms  reid ms  track ms
--------------------------------------------------------
KITTI-17                20.43     13.3     31.5       4.1
MOT16-09                14.30     17.0     41.7      11.2
MOT16-11                14.90     17.4     39.4      10.3
PETS09-S2L1             16.85     16.3     36.0       7.1
TUD-Campus              12.87     18.2     48.0      11.5
TUD-Stadtmitte          17.97     13.6     35.8       6.1
--------------------------------------------------------
MEAN                    16.22

Results: /content/DeepSORT_Project_CV/results/tracking/yolo_osnet_pv
Evaluate: python scripts/run_eval.py --tracker-name yolo_osnet_pv --results-dir /content/DeepSORT_Project_CV/results/tracking/yolo_osnet_pv

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 4 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_osnet_pv

1 eval_sequence(KITTI-17, yolo_osnet_pv)                                 0.1459 sec
2 eval_sequence(PETS09-S2L1, yolo_osnet_pv)                              0.8722 sec
3 eval_sequence(TUD-Campus, yolo_osnet_pv)                               0.0798 sec
4 eval_sequence(TUD-Stadtmitte, yolo_osnet_pv)                           0.2051 sec

All sequences for yolo_osnet_pv finished in 1.30 seconds

HOTA: yolo_osnet_pv-pedestrian     HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
KITTI-17                           55.708    56.522    54.955    65.724    68.638    59.582    74.801    79.826    60.073    76.311    74.929    57.179
PETS09-S2L1                        53.103    63.376    44.572    73.081    70.377    56.934    59.3      80.021    57.05     72.442    75.366    54.596
TUD-Campus                         47.956    47.445    48.649    66.046    55.269    60.149    63.451    79.583    56.67     65.199    73.903    48.184
TUD-Stadtmitte                     55.113    60.653    50.175    66.878    73.981    63.936    61.676    80.957    57.917    72.981    76.716    55.988
COMBINED                           53.406    61.179    46.703    70.875    69.808    58.523    61.4      80.136    57.518    72.494    75.466    54.708

CLEAR: yolo_osnet_pv-pedestrian    MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
KITTI-17                           65.154    77.057    66.471    81.113    84.709    55.556    44.444    0         46.544    554       129       100       9         5         4         0         11
PETS09-S2L1                        79.513    76.698    80.116    91.979    88.576    84.211    15.789    0         58.08     4117      359       531       27        16        3         0         86
TUD-Campus                         47.354    75.926    48.189    83.844    70.163    50        50        0         27.169    301       58        128       3         4         4         0         7
TUD-Stadtmitte                     74.913    77.788    75.346    82.872    91.675    70        30        0         56.506    958       198       87        5         7         3         0         10
COMBINED                           75.517    76.869    76.176    88.852    87.515    69.565    30.435    0         54.964    5930      744       846       44        32        14        0         114

Identity: yolo_osnet_pv-pedestrian IDF1      IDR       IDP       IDTP      IDFN      IDFP
KITTI-17                           75.093    73.499    76.758    502       181       152
PETS09-S2L1                        69.684    71.023    68.395    3179      1297      1469
TUD-Campus                         68.528    75.209    62.937    270       89        159
TUD-Stadtmitte                     69.332    66.003    73.014    763       393       282
COMBINED                           70.097    70.632    69.569    4714      1960      2062

Count: yolo_osnet_pv-pedestrian    Dets      GT_Dets   IDs       GT_IDs
KITTI-17                           654       683       13        9
PETS09-S2L1                        4648      4476      30        19
TUD-Campus                         429       359       12        8
TUD-Stadtmitte                     1045      1156      12        10
COMBINED                           6776      6674      67        46

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 2 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating yolo_osnet_pv

5 eval_sequence(MOT16-09, yolo_osnet_pv)                                 0.4966 sec
6 eval_sequence(MOT16-11, yolo_osnet_pv)                                 0.7016 sec

All sequences for yolo_osnet_pv finished in 1.20 seconds

HOTA: yolo_osnet_pv-pedestrian     HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
MOT16-09                           42.036    49.739    35.703    54.183    76.1      45.657    56.36     82.646    43.959    55.026    77.269    42.518
MOT16-11                           47.428    49.978    45.46     54.155    79.161    57.886    64.708    84.88     49.524    58.277    80.096    46.677
COMBINED                           45.573    49.87     42.09     54.165    78.018    53.665    61.961    84.061    47.65     57.113    79.04     45.142

CLEAR: yolo_osnet_pv-pedestrian    MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
MOT16-09                           59.464    80.66     60.32     65.76     92.359    36        52        12        46.745    3457      1800      286       45        9         13        3         82
MOT16-11                           53.455    83.853    53.739    61.075    89.277    21.739    34.783    43.478    43.593    5603      3571      673       26        15        24        30        53
COMBINED                           55.644    82.634    56.136    62.782    90.428    25.532    39.362    35.106    44.742    9060      5371      959       71        24        37        33        135

Identity: yolo_osnet_pv-pedestrian IDF1      IDR       IDP       IDTP      IDFN      IDFP
MOT16-09                           53        45.368    63.719    2385      2872      1358
MOT16-11                           53.515    45.062    65.87     4134      5040      2142
COMBINED                           53.325    45.174    65.066    6519      7912      3500

Count: yolo_osnet_pv-pedestrian    Dets      GT_Dets   IDs       GT_IDs
MOT16-09                           3743      5257      33        25
MOT16-11                           6276      9174      48        69
COMBINED                           10019     14431     81        94

=== HOTA summary (TrackEval) ===

Tracker: yolo_osnet_pv
Sequence                 HOTA     MOTA     IDF1
------------------------------------------------
KITTI-17                55.71    65.15    75.09
MOT16-09                42.04    59.46    53.00
MOT16-11                47.43    53.46    53.51
PETS09-S2L1             53.10    79.51    69.68
TUD-Campus              47.96    47.35    68.53
TUD-Stadtmitte          55.11    74.91    69.33
------------------------------------------------
MEAN (6 videos)         50.22

Saved: {'csv': 'results/eval/summary.csv', 'json': 'results/eval/summary.json'}

In [18]:
# Сравните ReID-модели по HOTA без влияния ошибок детектора.
for REID in ["osnet", "resnet50", "resnet50_ibn", "fastreid"]:
    !python scripts/run_tracker.py --gt-detections --reid {REID} --tracker-name gtdet_{REID}
    !python scripts/run_eval.py --tracker-name gtdet_{REID} --results-dir results/tracking/gtdet_{REID}

Detector: GT-boxes | ReID: osnet | mask_background: False | identity: False | tracker_name: gtdet_osnet
/usr/local/lib/python3.12/dist-packages/torchreid/models/osnet.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(cached_file)
Successfully loaded imagenet pretrained weights from "/root/.cache/torch/checkpoints/osnet_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

Tracking TUD-Campus ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  TUD-Campus: 15.79 FPS (det 0.0ms | reid 51.4ms | track 11.9ms)

Tracking TUD-Stadtmitte ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  TUD-Stadtmitte: 27.16 FPS (det 0.0ms | reid 32.2ms | track 4.5ms)

Tracking KITTI-17 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  KITTI-17: 20.95 FPS (det 0.0ms | reid 38.9ms | track 8.8ms)

Tracking PETS09-S2L1 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  PETS09-S2L1: 23.57 FPS (det 0.0ms | reid 35.3ms | track 7.1ms)

Tracking MOT16-09 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  MOT16-09: 18.51 FPS (det 0.1ms | reid 43.4ms | track 10.5ms)

Tracking MOT16-11 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  MOT16-11: 17.50 FPS (det 0.1ms | reid 45.1ms | track 12.0ms)

=== Tracking FPS summary ===
Sequence                  FPS   det ms  reid ms  track ms
--------------------------------------------------------
KITTI-17                20.95      0.0     38.9       8.8
MOT16-09                18.51      0.1     43.4      10.5
MOT16-11                17.50      0.1     45.1      12.0
PETS09-S2L1             23.57      0.0     35.3       7.1
TUD-Campus              15.79      0.0     51.4      11.9
TUD-Stadtmitte          27.16      0.0     32.2       4.5
--------------------------------------------------------
MEAN                    20.58

Results: /content/DeepSORT_Project_CV/results/tracking/gtdet_osnet
Evaluate: python scripts/run_eval.py --tracker-name gtdet_osnet --results-dir /content/DeepSORT_Project_CV/results/tracking/gtdet_osnet

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 4 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating gtdet_osnet

1 eval_sequence(KITTI-17, gtdet_osnet)                                   0.0894 sec
2 eval_sequence(PETS09-S2L1, gtdet_osnet)                                0.5114 sec
3 eval_sequence(TUD-Campus, gtdet_osnet)                                 0.0503 sec
4 eval_sequence(TUD-Stadtmitte, gtdet_osnet)                             0.1164 sec

All sequences for gtdet_osnet finished in 0.77 seconds

HOTA: gtdet_osnet-pedestrian       HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
KITTI-17                           82.299    82.185    82.444    86.938    88.362    87.048    88.42     89.125    84.627    95.765    87.346    83.646
PETS09-S2L1                        86.791    93.461    80.604    95.663    96.222    87.002    89.659    94.62     87.792    91.532    94.178    86.203
TUD-Campus                         82.693    84.645    80.845    88.315    90.846    89.256    86.087    90.638    84.486    91.982    89.702    82.509
TUD-Stadtmitte                     91.51     93.748    89.361    96.044    97.221    96.57     91.708    96.685    92.641    94.792    96.083    91.079
COMBINED                           87.027    91.598    82.746    94.441    95.312    89.177    90.098    94.24     88.397    92.57     93.583    86.63

CLEAR: gtdet_osnet-pedestrian      MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
KITTI-17                           95.754    87.624    96.047    97.218    98.81     100       0         0         83.723    664       19        8         2         9         0         0         1
PETS09-S2L1                        98.525    94.369    98.749    99.084    99.663    100       0         0         92.946    4435      41        15        10        19        0         0         3
TUD-Campus                         94.986    89.702    94.986    96.1      98.854    87.5      12.5      0         85.089    345       14        4         0         7         1         0         0
TUD-Stadtmitte                     97.405    96.261    97.405    98.097    99.299    100       0         0         93.737    1134      22        8         0         10        0         0         0
COMBINED                           97.857    93.77     98.037    98.562    99.471    97.826    2.1739    0         91.717    6578      96        35        12        45        1         0         4

Identity: gtdet_osnet-pedestrian   IDF1      IDR       IDP       IDTP      IDFN      IDFP
KITTI-17                           96.827    96.047    97.619    656       27        16
PETS09-S2L1                        87.654    87.399    87.91     3912      564       538
TUD-Campus                         91.243    89.972    92.55     323       36        26
TUD-Stadtmitte                     93.647    93.08     94.221    1076      80        66
COMBINED                           89.817    89.407    90.231    5967      707       646

Count: gtdet_osnet-pedestrian      Dets      GT_Dets   IDs       GT_IDs
KITTI-17                           672       683       9         9
PETS09-S2L1                        4450      4476      20        19
TUD-Campus                         349       359       7         8
TUD-Stadtmitte                     1142      1156      9         10
COMBINED                           6613      6674      45        46

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 2 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating gtdet_osnet

5 eval_sequence(MOT16-09, gtdet_osnet)                                   0.4208 sec
6 eval_sequence(MOT16-11, gtdet_osnet)                                   0.7595 sec

All sequences for gtdet_osnet finished in 1.18 seconds

HOTA: gtdet_osnet-pedestrian       HOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
MOT16-09                           62.959    72.9      54.405    75.559    93.882    61.092    86.021    93.656    64.115    68.261    92.202    62.938
MOT16-11                           74.831    82.775    67.667    84.473    96.568    71.595    92.985    95.034    75.601    78.117    94.758    74.021
COMBINED                           70.692    79.121    63.185    81.226    95.641    68.049    90.64     94.559    71.638    74.682    93.874    70.107

CLEAR: gtdet_osnet-pedestrian      MOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
MOT16-09                           79.399    93.038    79.989    80.236    99.693    76        24        0         73.813    4218      1039      13        31        19        6         0         39
MOT16-11                           86.44     94.758    86.647    87.061    99.526    68.116    30.435    1.4493    81.876    7987      1187      38        19        47        21        1         29
COMBINED                           83.875    94.163    84.221    84.575    99.584    70.213    28.723    1.0638    78.939    12205     2226      51        50        66        27        1         68

Identity: gtdet_osnet-pedestrian   IDF1      IDR       IDP       IDTP      IDFN      IDFP
MOT16-09                           68.339    61.67     76.625    3242      2015      989
MOT16-11                           78.284    73.381    83.888    6732      2442      1293
COMBINED                           74.748    69.115    81.381    9974      4457      2282

Count: gtdet_osnet-pedestrian      Dets      GT_Dets   IDs       GT_IDs
MOT16-09                           4231      5257      43        25
MOT16-11                           8025      9174      83        69
COMBINED                           12256     14431     126       94

=== HOTA summary (TrackEval) ===

Tracker: gtdet_osnet
Sequence                 HOTA     MOTA     IDF1
------------------------------------------------
KITTI-17                82.30    95.75    96.83
MOT16-09                62.96    79.40    68.34
MOT16-11                74.83    86.44    78.28
PETS09-S2L1             86.79    98.53    87.65
TUD-Campus              82.69    94.99    91.24
TUD-Stadtmitte          91.51    97.40    93.65
------------------------------------------------
MEAN (6 videos)         80.18

Saved: {'csv': 'results/eval/summary.csv', 'json': 'results/eval/summary.json'}
Detector: GT-boxes | ReID: resnet50 | mask_background: False | identity: False | tracker_name: gtdet_resnet50
Traceback (most recent call last):
  File "/content/DeepSORT_Project_CV/scripts/run_tracker.py", line 242, in <module>
    main()
  File "/content/DeepSORT_Project_CV/scripts/run_tracker.py", line 179, in main
    reid = create_reid_extractor(args.reid, reid_cfg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/DeepSORT_Project_CV/reid/base.py", line 124, in create_reid_extractor
    return TorchReIDExtractor(model_name=model_name, **cfg)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/DeepSORT_Project_CV/reid/torchreid_ext.py", line 149, in __init__
    self.model = _build_torchreid_model(model_name, checkpoint)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/DeepSORT_Project_CV/reid/torchreid_ext.py", line 131, in _build_torchreid_model
    _load_pretrained_weights(model, checkpoint)
  File "/content/DeepSORT_Project_CV/reid/torchreid_ext.py", line 92, in _load_pretrained_weights
    state_dict = _load_torchreid_checkpoint(checkpoint_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/DeepSORT_Project_CV/reid/torchreid_ext.py", line 67, in _load_torchreid_checkpoint
    raise ValueError(f"Unexpected checkpoint format: {checkpoint_path}")
ValueError: Unexpected checkpoint format: resources/models/torchreid/market1501_resnet50.pth

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True
Tracker file not found: /tmp/trackeval_g7mzwld8/gtdet_resnet50/data/TUD-Campus.txt
Traceback (most recent call last):
  File "/content/DeepSORT_Project_CV/scripts/run_eval.py", line 50, in <module>
    main()
  File "/content/DeepSORT_Project_CV/scripts/run_eval.py", line 45, in main
    report = run_eval_plan(plan, use_symlinks=not args.copy_instead_of_symlink)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/DeepSORT_Project_CV/eval/trackeval_wrap.py", line 239, in run_eval_plan
    raw_by_benchmark[benchmark.name] = _run_benchmark(
                                       ^^^^^^^^^^^^^^^
  File "/content/DeepSORT_Project_CV/eval/trackeval_wrap.py", line 145, in _run_benchmark
    dataset = trackeval.datasets.MotChallenge2DBox(dataset_config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/trackeval/datasets/mot_challenge_2d_box.py", line 126, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: gtdet_resnet50/data/TUD-Campus.txt
Detector: GT-boxes | ReID: resnet50_ibn | mask_background: False | identity: False | tracker_name: gtdet_resnet50_ibn
/content/DeepSORT_Project_CV/reid/fastreid_ext.py:32: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(checkpoint_path, map_location="cpu")

Tracking TUD-Campus ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  TUD-Campus: 21.50 FPS (det 0.1ms | reid 32.4ms | track 14.1ms)

Tracking TUD-Stadtmitte ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  TUD-Stadtmitte: 18.24 FPS (det 0.0ms | reid 33.0ms | track 21.8ms)

Tracking KITTI-17 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  KITTI-17: 33.54 FPS (det 0.0ms | reid 22.7ms | track 7.0ms)

Tracking PETS09-S2L1 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  PETS09-S2L1: 16.92 FPS (det 0.0ms | reid 35.0ms | track 24.0ms)

Tracking MOT16-09 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  MOT16-09: 11.82 FPS (det 0.1ms | reid 46.1ms | track 38.4ms)

Tracking MOT16-11 ... params=TrackerParams(min_confidence=0.3, min_detection_height=0, nms_max_overlap=1.0, max_cosine_distance=0.2, nn_budget=100)
  MOT16-11: 11.29 FPS (det 0.1ms | reid 48.2ms | track 40.3ms)

=== Tracking FPS summary ===
Sequence                  FPS   det ms  reid ms  track ms
--------------------------------------------------------
KITTI-17                33.54      0.0     22.7       7.0
MOT16-09                11.82      0.1     46.1      38.4
MOT16-11                11.29      0.1     48.2      40.3
PETS09-S2L1             16.92      0.0     35.0      24.0
TUD-Campus              21.50      0.1     32.4      14.1
TUD-Stadtmitte          18.24      0.0     33.0      21.8
--------------------------------------------------------
MEAN                    18.88

Results: /content/DeepSORT_Project_CV/results/tracking/gtdet_resnet50_ibn
Evaluate: python scripts/run_eval.py --tracker-name gtdet_resnet50_ibn --results-dir /content/DeepSORT_Project_CV/results/tracking/gtdet_resnet50_ibn

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity']
THRESHOLD            : 0.5
PRINT_CONFIG         : True

Evaluating 1 tracker(s) on 4 sequence(s) for 1 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating gtdet_resnet50_ibn

1 eval_sequence(KITTI-17, gtdet_resnet50_ibn)                            0.1795 sec
2 eval_sequence(PETS09-S2L1, gtdet_resnet50_ibn)                         0.8808 sec
3 eval_sequence(TUD-Campus, gtdet_resnet50_ibn)                          0.0810 sec
4 eval_sequence(TUD-Stadtmitte, gtdet_resnet50_ibn)                      0.2207 sec

All sequences for gtdet_resnet50_ibn finished in 1.36 seconds

HOTA: gtdet_resnet50_ibn-pedestrianHOTA      DetA      AssA      DetRe     DetPr     AssRe     AssPr     LocA      OWTA      HOTA(0)   LocA(0)   HOTALocA(0)
KITTI-17                           78.671    82.614    75.086    87.162    88.589    81.256    81.432    89.147    80.896    89.787    87.545    78.605
PETS09-S2L1                        84.776    94.212    76.29     96.096    96.614    87.268    85.666    94.797    85.602    88.769    94.552    83.933
TUD-Campus                         82.693    84.645    80.845    88.315    90.846    89.256    86.087    90.638    84.486    91.982    89.702    82.509
TUD-Stadtmitte                     91.51     93.748    89.361    96.044    97.221    96.57     91.708    96.685    92.641    94.792    96.083    91.079
COMBINED                           85.31     92.127    79.063    94.754    95.599    88.763    86.672    94.361    86.552    90.119    93.855    84.582

CLEAR: gtdet_resnet50_ibn-pedestrianMOTA      MOTP      MODA      CLR_Re    CLR_Pr    MTR       PTR       MLR       sMOTA     CLR_TP    CLR_FN    CLR_FP    IDSW      MT        PT        ML        Frag
KITTI-17                           95.461    87.592    96.34     97.365    98.958    100       0         0         83.381    665       18        7         6         9         0         0         0
PETS09-S2L1                        98.749    94.571    98.838    99.151    99.686    100       0         0         93.366    4438      38        14        4         19        0         0         2
TUD-Campus                         94.986    89.702    94.986    96.1      98.854    87.5      12.5      0         85.089    345       14        4         0         7         1         0         0
TUD-Stadtmitte                     97.405    96.261    97.405    98.097    99.299    100       0         0         93.737    1134      22        8         0         10        0         0         0
COMBINED                           97.977    93.902    98.127    98.622    99.501    97.826    2.1739    0         91.963    6582      92        33        10        45        1         0         2

Identity: gtdet_resnet50_ibn-pedestrianIDF1      IDR       IDP       IDTP      IDFN      IDFP
KITTI-17                           87.823    87.116    88.542    595       88        77
PETS09-S2L1                        83.333    83.11     83.558    3720      756       732
TUD-Campus                         91.243    89.972    92.55     323       36        26
TUD-Stadtmitte                     93.647    93.08     94.221    1076      80        66

In [19]:
!zip -r project_outputs.zip \
    results/baseline/original/ \
    results/tracking/ \
    results/detectors/ \
    results/reid/ \
    results/identity/ \
    results/param_sweep/ \
    results/identity_sweep/ \
    overlays/

from google.colab import files
files.download("project_outputs.zip")

	zip warning: name not matched: results/reid/
  adding: results/baseline/original/ (stored 0%)
  adding: results/baseline/original/TUD-Campus.txt (deflated 65%)
  adding: results/baseline/original/TUD-Stadtmitte.txt (deflated 68%)
  adding: results/baseline/original/MOT16-09.txt (deflated 68%)
  adding: results/baseline/original/MOT16-11.txt (deflated 68%)
  adding: results/baseline/original/KITTI-17.txt (deflated 66%)
  adding: results/baseline/original/PETS09-S2L1.txt (deflated 70%)
  adding: results/tracking/ (stored 0%)
  adding: results/tracking/gtdet_osnet/ (stored 0%)
  adding: results/tracking/gtdet_osnet/TUD-Campus.txt (deflated 65%)
  adding: results/tracking/gtdet_osnet/TUD-Stadtmitte.txt (deflated 70%)
  adding: results/tracking/gtdet_osnet/MOT16-09.txt (deflated 68%)
  adding: results/tracking/gtdet_osnet/MOT16-11.txt (deflated 68%)
  adding: results/tracking/gtdet_osnet/KITTI-17.txt (deflated 66%)
  adding: results/tracking/gtdet_osnet/PETS09-S2L1.txt (deflated 68%)
  adding: results/tracking/mmdet_osnet/ (stored 0%)
  adding: results/tracking/mmdet_osnet/TUD-Campus.txt (deflated 66%)
  adding: results/tracking/mmdet_osnet/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/tracking/mmdet_osnet/MOT16-09.txt (deflated 68%)
  adding: results/tracking/mmdet_osnet/MOT16-11.txt (deflated 67%)
  adding: results/tracking/mmdet_osnet/KITTI-17.txt (deflated 66%)
  adding: results/tracking/mmdet_osnet/PETS09-S2L1.txt (deflated 68%)
  adding: results/tracking/yolo_seg_osnet_seg/ (stored 0%)
  adding: results/tracking/yolo_seg_osnet_seg/TUD-Campus.txt (deflated 65%)
  adding: results/tracking/yolo_seg_osnet_seg/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/tracking/yolo_seg_osnet_seg/MOT16-09.txt (deflated 67%)
  adding: results/tracking/yolo_seg_osnet_seg/MOT16-11.txt (deflated 67%)
  adding: results/tracking/yolo_seg_osnet_seg/KITTI-17.txt (deflated 65%)
  adding: results/tracking/yolo_seg_osnet_seg/PETS09-S2L1.txt (deflated 68%)
  adding: results/tracking/gtdet_resnet50/ (stored 0%)
  adding: results/tracking/sweep_summary.json (deflated 66%)
  adding: results/tracking/sweep_summary.csv (deflated 38%)
  adding: results/tracking/nanodet_osnet/ (stored 0%)
  adding: results/tracking/nanodet_osnet/TUD-Campus.txt (deflated 66%)
  adding: results/tracking/nanodet_osnet/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/tracking/nanodet_osnet/MOT16-09.txt (deflated 68%)
  adding: results/tracking/nanodet_osnet/MOT16-11.txt (deflated 67%)
  adding: results/tracking/nanodet_osnet/KITTI-17.txt (deflated 67%)
  adding: results/tracking/nanodet_osnet/PETS09-S2L1.txt (deflated 69%)
  adding: results/tracking/yolo_osnet_pv/ (stored 0%)
  adding: results/tracking/yolo_osnet_pv/TUD-Campus.txt (deflated 65%)
  adding: results/tracking/yolo_osnet_pv/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/tracking/yolo_osnet_pv/MOT16-09.txt (deflated 67%)
  adding: results/tracking/yolo_osnet_pv/MOT16-11.txt (deflated 67%)
  adding: results/tracking/yolo_osnet_pv/KITTI-17.txt (deflated 66%)
  adding: results/tracking/yolo_osnet_pv/PETS09-S2L1.txt (deflated 68%)
  adding: results/tracking/yolo_osnet/ (stored 0%)
  adding: results/tracking/yolo_osnet/TUD-Campus.txt (deflated 65%)
  adding: results/tracking/yolo_osnet/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/tracking/yolo_osnet/MOT16-09.txt (deflated 67%)
  adding: results/tracking/yolo_osnet/MOT16-11.txt (deflated 67%)
  adding: results/tracking/yolo_osnet/KITTI-17.txt (deflated 66%)
  adding: results/tracking/yolo_osnet/PETS09-S2L1.txt (deflated 68%)
  adding: results/tracking/yolo_osnet_id/ (stored 0%)
  adding: results/tracking/yolo_osnet_id/MOT16-11_identity.csv (deflated 15%)
  adding: results/tracking/yolo_osnet_id/TUD-Stadtmitte_identity.csv (deflated 15%)
  adding: results/tracking/yolo_osnet_id/TUD-Campus.txt (deflated 65%)
  adding: results/tracking/yolo_osnet_id/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/tracking/yolo_osnet_id/MOT16-09_identity.csv (deflated 15%)
  adding: results/tracking/yolo_osnet_id/MOT16-09.txt (deflated 67%)
  adding: results/tracking/yolo_osnet_id/TUD-Campus_identity.csv (deflated 15%)
  adding: results/tracking/yolo_osnet_id/KITTI-17_identity.csv (deflated 15%)
  adding: results/tracking/yolo_osnet_id/PETS09-S2L1_identity.csv (deflated 15%)
  adding: results/tracking/yolo_osnet_id/MOT16-11.txt (deflated 67%)
  adding: results/tracking/yolo_osnet_id/KITTI-17.txt (deflated 66%)
  adding: results/tracking/yolo_osnet_id/PETS09-S2L1.txt (deflated 68%)
  adding: results/tracking/yolo_resnet50_ibn/ (stored 0%)
  adding: results/tracking/yolo_resnet50_ibn/TUD-Campus.txt (deflated 65%)
  adding: results/tracking/yolo_resnet50_ibn/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/tracking/yolo_resnet50_ibn/MOT16-09.txt (deflated 67%)
  adding: results/tracking/yolo_resnet50_ibn/MOT16-11.txt (deflated 67%)
  adding: results/tracking/yolo_resnet50_ibn/KITTI-17.txt (deflated 66%)
  adding: results/tracking/yolo_resnet50_ibn/PETS09-S2L1.txt (deflated 68%)
  adding: results/tracking/gtdet_fastreid/ (stored 0%)
  adding: results/tracking/gtdet_fastreid/TUD-Campus.txt (deflated 65%)
  adding: results/tracking/gtdet_fastreid/TUD-Stadtmitte.txt (deflated 70%)
  adding: results/tracking/gtdet_fastreid/MOT16-09.txt (deflated 67%)
  adding: results/tracking/gtdet_fastreid/MOT16-11.txt (deflated 68%)
  adding: results/tracking/gtdet_fastreid/KITTI-17.txt (deflated 66%)
  adding: results/tracking/gtdet_fastreid/PETS09-S2L1.txt (deflated 68%)
  adding: results/tracking/gtdet_resnet50_ibn/ (stored 0%)
  adding: results/tracking/gtdet_resnet50_ibn/TUD-Campus.txt (deflated 65%)
  adding: results/tracking/gtdet_resnet50_ibn/TUD-Stadtmitte.txt (deflated 70%)
  adding: results/tracking/gtdet_resnet50_ibn/MOT16-09.txt (deflated 67%)
  adding: results/tracking/gtdet_resnet50_ibn/MOT16-11.txt (deflated 68%)
  adding: results/tracking/gtdet_resnet50_ibn/KITTI-17.txt (deflated 66%)
  adding: results/tracking/gtdet_resnet50_ibn/PETS09-S2L1.txt (deflated 68%)
  adding: results/detectors/ (stored 0%)
  adding: results/detectors/summary.csv (deflated 50%)
  adding: results/detectors/summary.json (deflated 74%)
  adding: results/identity/ (stored 0%)
  adding: results/identity/summary.csv (deflated 51%)
  adding: results/identity/summary.json (deflated 74%)
  adding: results/param_sweep/ (stored 0%)
  adding: results/param_sweep/sweep_max_cosine_distance.csv (deflated 34%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.1/ (stored 0%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.1/TUD-Campus.txt (deflated 65%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.1/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.1/MOT16-09.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.1/MOT16-11.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.1/KITTI-17.txt (deflated 66%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.1/PETS09-S2L1.txt (deflated 68%)
  adding: results/param_sweep/sweep_max_cosine_distance.json (deflated 65%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.4/ (stored 0%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.4/TUD-Campus.txt (deflated 65%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.4/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.4/MOT16-09.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.4/MOT16-11.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.4/KITTI-17.txt (deflated 65%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.4/PETS09-S2L1.txt (deflated 68%)
  adding: results/param_sweep/sweep_min_confidence.json (deflated 69%)
  adding: results/param_sweep/sweep_min_confidence.csv (deflated 40%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.5/ (stored 0%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.5/TUD-Campus.txt (deflated 65%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.5/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.5/MOT16-09.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.5/MOT16-11.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.5/KITTI-17.txt (deflated 65%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.5/PETS09-S2L1.txt (deflated 68%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.3/ (stored 0%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.3/TUD-Campus.txt (deflated 65%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.3/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.3/MOT16-09.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.3/MOT16-11.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.3/KITTI-17.txt (deflated 66%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.3/PETS09-S2L1.txt (deflated 68%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.3/ (stored 0%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.3/TUD-Campus.txt (deflated 65%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.3/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.3/MOT16-09.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.3/MOT16-11.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.3/KITTI-17.txt (deflated 66%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.3/PETS09-S2L1.txt (deflated 68%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.2/ (stored 0%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.2/TUD-Campus.txt (deflated 65%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.2/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.2/MOT16-09.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.2/MOT16-11.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.2/KITTI-17.txt (deflated 66%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.2/PETS09-S2L1.txt (deflated 68%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.2/ (stored 0%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.2/TUD-Campus.txt (deflated 65%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.2/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.2/MOT16-09.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.2/MOT16-11.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.2/KITTI-17.txt (deflated 66%)
  adding: results/param_sweep/yolo_osnet__min_confidence_0.2/PETS09-S2L1.txt (deflated 68%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.4/ (stored 0%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.4/TUD-Campus.txt (deflated 65%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.4/TUD-Stadtmitte.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.4/MOT16-09.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.4/MOT16-11.txt (deflated 67%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.4/KITTI-17.txt (deflated 66%)
  adding: results/param_sweep/yolo_osnet__max_cosine_distance_0.4/PETS09-S2L1.txt (deflated 68%)
  adding: results/identity_sweep/ (stored 0%)
  adding: results/identity_sweep/sweep_radius.csv (deflated 47%)
  adding: results/identity_sweep/sweep_radius.json (deflated 76%)
  adding: results/identity_sweep/sweep_representation.csv (deflated 31%)
  adding: results/identity_sweep/sweep_representation.json (deflated 66%)
  adding: overlays/ (stored 0%)
  adding: overlays/best/ (stored 0%)
  adding: overlays/best/KITTI-17.avi (deflated 0%)
  adding: overlays/best/TUD-Campus.mp4 (deflated 0%)
  adding: overlays/best/TUD-Campus.avi (deflated 0%)
  adding: overlays/best/MOT16-11.avi (deflated 1%)
  adding: overlays/best/KITTI-17.mp4 (deflated 0%)
  adding: overlays/best/MOT16-09.mp4 (deflated 0%)
  adding: overlays/best/TUD-Stadtmitte.mp4 (deflated 0%)
  adding: overlays/best/PETS09-S2L1.mp4 (deflated 0%)
  adding: overlays/best/MOT16-11.mp4 (deflated 0%)
  adding: overlays/best/PETS09-S2L1.avi (deflated 0%)
  adding: overlays/best/MOT16-09.avi (deflated 1%)
  adding: overlays/best/TUD-Stadtmitte.avi (deflated 0%)
  adding: overlays/original/ (stored 0%)
  adding: overlays/original/KITTI-17.avi (deflated 0%)
  adding: overlays/original/TUD-Campus.mp4 (deflated 0%)
  adding: overlays/original/TUD-Campus.avi (deflated 0%)
  adding: overlays/original/MOT16-11.avi (deflated 1%)
  adding: overlays/original/KITTI-17.mp4 (deflated 0%)
  adding: overlays/original/MOT16-09.mp4 (deflated 0%)
  adding: overlays/original/TUD-Stadtmitte.mp4 (deflated 0%)
  adding: overlays/original/PETS09-S2L1.mp4 (deflated 0%)
  adding: overlays/original/MOT16-11.mp4 (deflated 0%)
  adding: overlays/original/PETS09-S2L1.avi (deflated 0%)
  adding: overlays/original/MOT16-09.avi (deflated 1%)
  adding: overlays/original/TUD-Stadtmitte.avi (deflated 0%)